"""DataEntry — notes 카테고리 진입점 (Cut 8 분할).

단일 진실의 원천은 list 자체. 로직은 ``core/registry.py``.
"""

from __future__ import annotations

from dartlab.core.dataEntry import ColumnMeta, DataEntry  # noqa: F401

_NOTES_ENTRIES: list[DataEntry] = [
    # notes — K-IFRS 주석
    # ═══════════════════════════════════════════════════════
    # Q1.2 (2026-04-21): notes entry 에 notesDispatch + extractor 추가 — notes.py 의
    # _NOTES_DISPATCH 하드코딩 제거 목적. 이제 registry 가 dispatch 의 단일 출처.
    DataEntry(
        name="notes.receivables",
        label="매출채권",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 매출채권 주석. 채권 잔액 및 대손충당금 내역.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "매출채권"),
        requires="panel",
    ),
    DataEntry(
        name="notes.inventory",
        label="재고자산",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 재고자산 주석. 원재료/재공품/제품 내역별 금액.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "재고자산"),
        requires="panel",
    ),
    DataEntry(
        name="notes.tangibleAsset",
        label="유형자산(주석)",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 유형자산 변동 주석. 토지, 건물, 기계 등 항목별 변동.",
        extractor=lambda r: r.movementDf,
        notesDispatch=("tangibleAsset", "유형자산"),
        requires="panel",
    ),
    DataEntry(
        name="notes.intangibleAsset",
        label="무형자산",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 무형자산 주석. 영업권, 개발비 등 항목별 변동.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "무형자산"),
        requires="panel",
    ),
    DataEntry(
        name="notes.investmentProperty",
        label="투자부동산",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 투자부동산 주석. 공정가치 및 변동 내역.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "투자부동산"),
        requires="panel",
    ),
    DataEntry(
        name="notes.affiliates",
        label="관계기업(주석)",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 관계기업 투자 주석. 지분법 적용 내역.",
        extractor=lambda r: r.movementDf,
        notesDispatch=("affiliate", "관계기업"),
        requires="panel",
    ),
    DataEntry(
        name="notes.borrowings",
        label="차입금",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 차입금 주석. 단기/장기 차입 잔액 및 이자율.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "차입금"),
        requires="panel",
    ),
    DataEntry(
        name="notes.provisions",
        label="충당부채",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 충당부채 주석. 판매보증, 소송, 복구 등.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "충당부채"),
        requires="panel",
    ),
    DataEntry(
        name="notes.eps",
        label="주당이익",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 주당이익 주석. 기본/희석 EPS 계산 내역.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "주당이익"),
        requires="panel",
    ),
    DataEntry(
        name="notes.lease",
        label="리스",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 리스 주석. 사용권자산, 리스부채 내역.",
        extractor=lambda r: r.tableDf,
        notesDispatch=("notesDetail", "리스"),
        requires="panel",
    ),
    DataEntry(
        name="notes.segments",
        label="부문정보(주석)",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 부문정보 주석. 사업부문별 상세 데이터.",
        extractor=lambda r: r.revenue,
        notesDispatch=("segments", "부문정보"),
        canonicalKey="NT_D871100",
        noteShape="composition",
        requires="panel",
    ),
    DataEntry(
        name="notes.costByNature",
        label="비용의성격별분류(주석)",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 비용의 성격별 분류 주석.",
        extractor=lambda r: r.timeSeries,
        notesDispatch=("costByNature", "비용의성격별분류"),
        canonicalKey="NT_D834300",
        noteShape="lineitem",
        requires="panel",
    ),
    # ── Q2 (2026-06-29): 고가치 미등록 노트 — extractNoteView(canonicalKey, noteShape) SSOT 추출. ──
    DataEntry(
        name="notes.revenueRegion",
        label="지역별 매출",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 매출액 주석 — 지역(국내/미국/중국/유럽…)별 매출. '어디서 버나(지역)'.",
        notesDispatch=("noteView", "지역별매출"),
        canonicalKey="NT_D831150",
        noteShape="lineitem",
        requires="panel",
    ),
    DataEntry(
        name="notes.sga",
        label="판매비와관리비",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 판매비와관리비 주석 — 급여·복리후생·지급수수료 등 판관비 분해.",
        notesDispatch=("noteView", "판매비와관리비"),
        canonicalKey="NT_D834310",
        noteShape="lineitem",
        requires="panel",
    ),
    DataEntry(
        name="notes.employeeBenefit",
        label="종업원급여",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 종업원급여 주석 — 급여·퇴직급여·확정급여채무 등 인건비 깊이.",
        notesDispatch=("noteView", "종업원급여"),
        canonicalKey="NT_D834480",
        noteShape="lineitem",
        requires="panel",
    ),
    DataEntry(
        name="notes.financeIncomeCost",
        label="금융수익·금융비용",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 금융수익 및 금융비용 주석 — 이자수익/이자비용/외환손익 등.",
        notesDispatch=("noteView", "금융손익"),
        canonicalKey="NT_D834330",
        noteShape="lineitem",
        requires="panel",
    ),
    DataEntry(
        name="notes.relatedParty",
        label="특수관계자 거래",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 특수관계자 거래 주석 — 거래상대별 매출/매입(계열 의존도). axisPath=상대사.",
        notesDispatch=("noteView", "특수관계자거래"),
        canonicalKey="NT_D818000",
        noteShape="composition",
        requires="panel",
    ),
    DataEntry(
        name="notes.incomeTax",
        label="법인세비용",
        category="notes",
        dataType="dataframe",
        description="K-IFRS 법인세비용 주석 — 당기/이연 법인세, 유효세율 산정 내역.",
        notesDispatch=("noteView", "법인세"),
        canonicalKey="NT_D835110",
        noteShape="lineitem",
        requires="panel",
    ),
    # ═══════════════════════════════════════════════════════
]
