"""재무제표와 K-IFRS note 추출 개념의 선언형 manifest."""

from __future__ import annotations

from dartlab.core.extractionCatalog.models import (
    DartSource,
    EdgarSource,
    ExtractionConcept,
    HonestNull,
)

# providers/edgar/docs/notesParsers._CATEGORY_TAGS 정본 mirror.
# L0가 L1을 import하지 않으므로 provider 순서에서 소비 방향을 수렴할 때까지 drift Guard로 보호한다.
EDGAR_NOTE_TAGS: dict[str, tuple[str, ...]] = {
    "inventory": (
        "InventoryFinishedGoods",
        "InventoryWorkInProcess",
        "InventoryRawMaterials",
        "InventoryNet",
        "InventoryGross",
        "InventoryAdjustments",
        "InventoryValuationReserves",
    ),
    "borrowings": (
        "LongTermDebt",
        "LongTermDebtNoncurrent",
        "LongTermDebtCurrent",
        "ShortTermBorrowings",
        "LinesOfCreditCurrent",
        "CommercialPaper",
        "NotesPayable",
        "SecuredDebt",
        "UnsecuredDebt",
    ),
    "tangibleAsset": (
        "PropertyPlantAndEquipmentGross",
        "PropertyPlantAndEquipmentNet",
        "AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment",
        "Land",
        "BuildingsAndImprovementsGross",
        "MachineryAndEquipmentGross",
        "ConstructionInProgressGross",
        "LeaseholdImprovementsGross",
    ),
    "intangibleAsset": (
        "Goodwill",
        "IntangibleAssetsNetExcludingGoodwill",
        "FiniteLivedIntangibleAssetsGross",
        "FiniteLivedIntangibleAssetsAccumulatedAmortization",
        "FiniteLivedIntangibleAssetsNet",
        "IndefiniteLivedIntangibleAssetsExcludingGoodwill",
        "CapitalizedComputerSoftwareGross",
        "CapitalizedComputerSoftwareNet",
    ),
    "receivables": (
        "AccountsReceivableNetCurrent",
        "AccountsReceivableGrossCurrent",
        "AllowanceForDoubtfulAccountsReceivableCurrent",
        "NotesReceivableNet",
        "ReceivablesNetCurrent",
    ),
    "provisions": (
        "ProductWarrantyAccrual",
        "LossContingencyAccrualAtCarryingValue",
        "RestructuringReserve",
        "EnvironmentalLossContingencyStatementOfFinancialPositionAccrual",
        "LitigationReserve",
        "AccruedLiabilitiesCurrent",
    ),
    "eps": (
        "EarningsPerShareBasic",
        "EarningsPerShareDiluted",
        "WeightedAverageNumberOfShareOutstandingBasicAndDiluted",
        "WeightedAverageNumberOfDilutedSharesOutstanding",
        "AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount",
    ),
    "segments": (
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "SegmentReportingInformationOperatingIncomeLoss",
        "SegmentReportingInformationRevenue",
    ),
    "costByNature": (
        "CostOfGoodsAndServicesSold",
        "SellingGeneralAndAdministrativeExpense",
        "ResearchAndDevelopmentExpense",
        "DepreciationAndAmortization",
        "LaborAndRelatedExpense",
        "AdvertisingExpense",
    ),
    "lease": (
        "OperatingLeaseRightOfUseAsset",
        "OperatingLeaseLiability",
        "FinanceLeaseRightOfUseAsset",
        "FinanceLeaseLiability",
        "OperatingLeasePayments",
        "OperatingLeaseCost",
    ),
    "affiliates": (
        "InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures",
        "EquityMethodInvestments",
        "EquityMethodInvestmentRealizedGainLossOnDisposal",
        "IncomeLossFromEquityMethodInvestments",
        "EquityMethodInvestmentDividendsOrDistributions",
        "EquityMethodInvestmentOwnershipPercentage",
        "PaymentsToAcquireEquityMethodInvestments",
        "PaymentsToAcquireBusinessesAndInterestInAffiliates",
        "EquityMethodInvestmentOtherThanTemporaryImpairment",
    ),
    "investmentProperty": (
        "RealEstateInvestmentPropertyNet",
        "RealEstateInvestmentPropertyAtCost",
        "RealEstateInvestmentPropertyAccumulatedDepreciation",
        "RealEstateInvestmentPropertyAtFairValue",
        "RealEstateHeldsale",
    ),
}


def _note(
    conceptId: str,
    label: str,
    dartKey: str,
    edgarTags: tuple[str, ...],
    *,
    axisType: str = "multiAxis",
    valueType: str = "amount",
    registered: bool = False,
    edgarNull: str | None = None,
) -> ExtractionConcept:
    """K-IFRS note 개념 한 행을 만든다."""
    edgar: EdgarSource | HonestNull
    edgar = HonestNull(edgarNull) if edgarNull is not None else EdgarSource("xbrlTag", edgarTags)
    return ExtractionConcept(
        conceptId=conceptId,
        category="note",
        label=label,
        dart=DartSource("note", dartKey),
        edgar=edgar,
        axisType=axisType,
        valueType=valueType,
        registered=registered,
    )


STATEMENTS: tuple[ExtractionConcept, ...] = (
    ExtractionConcept(
        "statement.is",
        "financialStatement",
        "손익계산서",
        DartSource("statement", "is"),
        EdgarSource("statement", ("Revenues", "NetIncomeLoss", "OperatingIncomeLoss")),
    ),
    ExtractionConcept(
        "statement.bs",
        "financialStatement",
        "재무상태표",
        DartSource("statement", "bs"),
        EdgarSource("statement", ("Assets", "Liabilities", "StockholdersEquity")),
    ),
    ExtractionConcept(
        "statement.cf",
        "financialStatement",
        "현금흐름표",
        DartSource("statement", "cf"),
        EdgarSource("statement", ("NetCashProvidedByUsedInOperatingActivities",)),
    ),
    ExtractionConcept(
        "statement.cis",
        "financialStatement",
        "포괄손익계산서",
        DartSource("statement", "cis"),
        EdgarSource("statement", ("ComprehensiveIncomeNetOfTax",)),
    ),
    ExtractionConcept(
        "statement.sce",
        "financialStatement",
        "자본변동표",
        DartSource("statement", "sce"),
        EdgarSource("statement", ("StockholdersEquity",)),
    ),
    ExtractionConcept(
        "statement.ratios",
        "financialStatement",
        "재무비율",
        DartSource("statement", "ratios"),
        EdgarSource("statement", ("Revenues", "Assets", "StockholdersEquity")),
        valueType="rate",
    ),
)

NOTES: tuple[ExtractionConcept, ...] = (
    # core/dataEntry.py에 등록된 12개 note.
    _note("note.inventory", "재고자산", "NT_D826380", EDGAR_NOTE_TAGS["inventory"], registered=True),
    _note("note.receivables", "매출채권", "NT_D822420", EDGAR_NOTE_TAGS["receivables"], registered=True),
    _note(
        "note.tangibleAsset",
        "유형자산",
        "NT_D822100",
        EDGAR_NOTE_TAGS["tangibleAsset"],
        axisType="movement",
        registered=True,
    ),
    _note("note.intangibleAsset", "무형자산", "NT_D823180", EDGAR_NOTE_TAGS["intangibleAsset"], registered=True),
    _note(
        "note.investmentProperty",
        "투자부동산",
        "NT_D825900",
        EDGAR_NOTE_TAGS["investmentProperty"],
        registered=True,
    ),
    _note(
        "note.affiliates",
        "관계기업",
        "NT_D825700",
        EDGAR_NOTE_TAGS["affiliates"],
        axisType="movement",
        registered=True,
    ),
    _note("note.borrowings", "차입금", "NT_D822400", EDGAR_NOTE_TAGS["borrowings"], registered=True),
    _note("note.provisions", "충당부채", "NT_D827570", EDGAR_NOTE_TAGS["provisions"], registered=True),
    _note("note.eps", "주당이익", "NT_D838000", EDGAR_NOTE_TAGS["eps"], registered=True),
    _note("note.lease", "리스", "NT_D832610", EDGAR_NOTE_TAGS["lease"], registered=True),
    _note("note.segments", "영업부문(주석)", "NT_D871100", EDGAR_NOTE_TAGS["segments"], registered=True),
    _note("note.costByNature", "비용의성격별분류", "NT_D834300", EDGAR_NOTE_TAGS["costByNature"], registered=True),
    # 고가치 first-class note 10개.
    _note(
        "note.regionalRevenue",
        "지역별매출",
        "NT_D831150",
        ("RevenueFromContractWithCustomerExcludingAssessedTax",),
        registered=True,
    ),
    _note(
        "note.sgAndA",
        "판매비와관리비",
        "NT_D834310",
        ("SellingGeneralAndAdministrativeExpense", "GeneralAndAdministrativeExpense"),
        registered=True,
    ),
    _note(
        "note.employeeBenefits",
        "종업원급여",
        "NT_D834480",
        ("DefinedBenefitPlanBenefitObligation", "DefinedBenefitPlanFairValueOfPlanAssets", "LaborAndRelatedExpense"),
        registered=True,
    ),
    _note(
        "note.financialIncomeExpense",
        "금융수익금융비용",
        "NT_D834330",
        ("InterestExpense", "InvestmentIncomeInterest", "InterestIncomeExpenseNet"),
        registered=True,
    ),
    _note(
        "note.relatedParty",
        "특수관계자거래",
        "NT_D818000",
        ("RelatedPartyTransactionAmountsOfTransaction", "RelatedPartyTransactionDueFromToRelatedPartyCurrent"),
        registered=True,
    ),
    _note(
        "note.tax",
        "법인세",
        "NT_D835110",
        ("IncomeTaxExpenseBenefit", "DeferredTaxAssetsNet", "CurrentIncomeTaxExpenseBenefit"),
        registered=True,
    ),
    _note(
        "note.contingencies",
        "우발부채약정",
        "NT_D827580",
        ("LossContingencyEstimateOfPossibleLoss", "UnrecordedUnconditionalPurchaseObligationBalanceSheetAmount"),
        valueType="text",
        registered=True,
    ),
    _note(
        "note.financialInstruments",
        "금융상품범주별",
        "NT_D822430",
        ("FinancialInstrumentsOwnedAtFairValue", "AvailableForSaleSecurities"),
        registered=True,
    ),
    _note(
        "note.capitalReserves",
        "자본및자본잉여금",
        "NT_D861200",
        ("AdditionalPaidInCapital", "CommonStockValue"),
        axisType="movement",
        registered=True,
    ),
    _note(
        "note.retainedEarnings",
        "이익잉여금",
        "NT_D861300",
        ("RetainedEarningsAccumulatedDeficit",),
        axisType="movement",
        registered=True,
    ),
    _note(
        "note.shareBasedComp",
        "주식기준보상",
        "NT_D834120",
        ("ShareBasedCompensation", "AllocatedShareBasedCompensationExpense"),
    ),
    # 전 종목 census에서 확인한 표준 K-IFRS note.
    _note(
        "note.financialRiskMgmt",
        "재무위험관리",
        "NT_D822390",
        (),
        valueType="text",
        edgarNull="US 는 파생상품·공정가치 노트로 분산, 단일 재무위험관리 fact 부재",
        registered=True,
    ),
    _note(
        "note.cashAndEquivalents",
        "현금및현금성자산",
        "NT_D822410",
        ("CashAndCashEquivalentsAtCarryingValue", "RestrictedCashAndCashEquivalents"),
        registered=True,
    ),
    _note(
        "note.otherIncomeExpense",
        "기타수익및기타비용",
        "NT_D834320",
        ("OtherNonoperatingIncomeExpense", "OtherOperatingIncomeExpenseNet"),
        registered=True,
    ),
    _note(
        "note.businessCombination",
        "사업결합",
        "NT_D817000",
        (
            "BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedNet",
            "BusinessCombinationConsiderationTransferred1",
        ),
        registered=True,
    ),
    _note(
        "note.subsequentEvents",
        "보고기간후사건",
        "NT_D815000",
        (),
        valueType="text",
        edgarNull="US SubsequentEvents 는 서술 TextBlock(수치 fact 부재)",
        registered=True,
    ),
    _note(
        "note.otherEquity",
        "기타자본항목",
        "NT_D861400",
        ("AccumulatedOtherComprehensiveIncomeLossNetOfTax",),
        axisType="movement",
        registered=True,
    ),
    _note(
        "note.restrictedFinancial",
        "사용제한금융상품",
        "NT_D822470",
        ("RestrictedCashAndCashEquivalents", "RestrictedCash"),
        registered=True,
    ),
    _note(
        "note.otherAssets",
        "기타유동및비유동자산",
        "NT_D822300",
        ("OtherAssetsCurrent", "OtherAssetsNoncurrent"),
        registered=True,
    ),
    _note(
        "note.otherLiabilities",
        "기타유동및비유동부채",
        "NT_D822310",
        ("OtherLiabilitiesCurrent", "OtherLiabilitiesNoncurrent"),
        registered=True,
    ),
    _note(
        "note.accountingPolicies",
        "유의적회계정책",
        "NT_D810000",
        (),
        valueType="text",
        edgarNull="US SignificantAccountingPolicies 는 서술 TextBlock(수치 fact 부재)",
        registered=True,
    ),
    _note(
        "note.fairValue",
        "공정가치측정",
        "NT_D823000",
        (
            "FairValueMeasurementsRecurringMember",
            "AssetsFairValueDisclosure",
            "FairValueMeasuredOnRecurringBasisUnobservableInputReconciliationRecurringBasisAssetValue",
        ),
        registered=True,
    ),
    _note(
        "note.criticalEstimates",
        "중요한회계추정및가정",
        "NT_D810010",
        (),
        valueType="text",
        edgarNull="US 는 critical accounting estimates 를 MD&A(Item 7) 서술로 공시(수치 fact 부재)",
        registered=True,
    ),
)

__all__ = ["EDGAR_NOTE_TAGS", "NOTES", "STATEMENTS"]
