// AUTO-GENERATED by scripts/buildMarimoShim.cjs — do not edit directly.
// Edit files in engine/marimo_shim/ instead.

export const MARIMO_SHIM_FILES: Record<string, string> = {

'/lib/python3.12/marimo/__init__.py': `from marimo import _ui as ui
from marimo._output.md import md
from marimo._output.html import Html
from marimo._layout.stacks import hstack, vstack
from marimo._layout.callout import callout
from marimo._layout.accordion import accordion
from marimo._layout.tabs import tabs
from marimo._layout.carousel import carousel
from marimo._layout.stat import stat
from marimo._layout.tree import tree
from marimo._layout.json_viewer import json
from marimo._layout.align import center, left, right
from marimo._layout.plain import plain
from marimo._layout.lazy import lazy
from marimo._output.media import image, video, audio
from marimo._output.display import as_html
from marimo._control import stop, MarimoStopError
from marimo._state import state

def App(**kwargs):
    return _AppStub(**kwargs)

class _AppStub:
    def __init__(self, **kwargs):
        self.kwargs = kwargs
    def cell(self, func=None, **kwargs):
        if func is not None:
            return func
        def decorator(f):
            return f
        return decorator
    def run(self):
        pass
`,

'/lib/python3.12/marimo/_control.py': `class MarimoStopError(Exception):
    def __init__(self, output=None):
        self.output = output
        super().__init__(str(output) if output else "Execution stopped")

def stop(predicate, output=None):
    if predicate:
        raise MarimoStopError(output)
`,

'/lib/python3.12/marimo/_layout/__init__.py': ``,

'/lib/python3.12/marimo/_layout/accordion.py': `from marimo._output.html import Html

def accordion(items, multiple=False, lazy=False, **kwargs):
    if isinstance(items, dict):
        entries = items.items()
    else:
        entries = items
    sections = []
    for title, content in entries:
        if hasattr(content, '_repr_html_'):
            inner = content._repr_html_()
        else:
            inner = str(content)
        sections.append(
            f'<details class="chani-accordion-item">'
            f'<summary>{title}</summary>'
            f'<div class="chani-accordion-body">{inner}</div>'
            f'</details>'
        )
    html = '<div class="chani-accordion">' + ''.join(sections) + '</div>'
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/align.py': `from marimo._output.html import Html

def _align(item, text_align):
    if hasattr(item, '_repr_html_'):
        inner = item._repr_html_()
    else:
        inner = str(item)
    html = f'<div style="text-align:{text_align};">{inner}</div>'
    return Html(html)

def center(item, **kwargs):
    return _align(item, 'center')

def left(item, **kwargs):
    return _align(item, 'left')

def right(item, **kwargs):
    return _align(item, 'right')
`,

'/lib/python3.12/marimo/_layout/callout.py': `from marimo._output.html import Html

_KIND_COLORS = {
    'neutral': '#71717a',
    'info': '#3b82f6',
    'warn': '#f59e0b',
    'success': '#22c55e',
    'danger': '#ef4444',
}

def callout(content, kind='neutral', **kwargs):
    color = _KIND_COLORS.get(kind, _KIND_COLORS['neutral'])
    if hasattr(content, '_repr_html_'):
        inner = content._repr_html_()
    else:
        inner = str(content)
    html = (
        f'<div class="chani-callout chani-callout-{kind}" '
        f'style="border-left:3px solid {color};padding:12px 16px;border-radius:6px;background:rgba(0,0,0,0.05);">'
        f'{inner}</div>'
    )
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/carousel.py': `from marimo._output.html import Html
from marimo._output.display import as_html
from marimo._output.md import md

def carousel(items, **kwargs):
    slides = []
    for item in items:
        if isinstance(item, str):
            rendered = md(item)._repr_html_()
        elif hasattr(item, '_repr_html_'):
            rendered = item._repr_html_()
        else:
            rendered = f'<div>{item}</div>'
        slides.append(rendered)

    total = len(slides)
    if total == 0:
        return Html('<div></div>')

    slide_divs = ''.join(
        f'<div class="chani-carousel-slide" data-slide="{i}" style="display:{("block" if i == 0 else "none")}">{s}</div>'
        for i, s in enumerate(slides)
    )

    uid = f'cc_{id(items)}'

    nav_js = (
        "var c=this.closest('.chani-carousel');"
        "var ss=c.querySelectorAll('.chani-carousel-slide');"
        "var cur=+c.dataset.current||0;"
        "var dir=this.dataset.dir==='next'?1:-1;"
        "ss[cur].style.display='none';"
        "cur=(cur+dir+ss.length)%ss.length;"
        "ss[cur].style.display='block';"
        "c.dataset.current=cur;"
        "c.querySelector('.chani-carousel-counter').textContent=(cur+1)+' / '+ss.length;"
    )

    html = (
        f'<div class="chani-carousel" id="{uid}" data-current="0" '
        f'style="border:1px solid var(--nb-border,#27272a);border-radius:8px;overflow:hidden;">'
        f'<div class="chani-carousel-track" style="padding:16px;">{slide_divs}</div>'
        f'<div class="chani-carousel-nav" style="display:flex;align-items:center;justify-content:space-between;'
        f'padding:8px 12px;border-top:1px solid var(--nb-border,#27272a);background:var(--nb-surface,#18181b);">'
        f'<button data-dir="prev" onclick="{nav_js}" '
        f'style="background:none;border:none;color:var(--nb-text,#fafafa);cursor:pointer;font-size:20px;padding:4px 8px;">&#8249;</button>'
        f'<span class="chani-carousel-counter" style="font-size:12px;color:var(--nb-text-muted,#71717a);">1 / {total}</span>'
        f'<button data-dir="next" onclick="{nav_js}" '
        f'style="background:none;border:none;color:var(--nb-text,#fafafa);cursor:pointer;font-size:20px;padding:4px 8px;">&#8250;</button>'
        f'</div></div>'
    )
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/json_viewer.py': `from marimo._output.html import Html
from marimo._layout.tree import _render_tree_node
import json as _json

def json(data, **kwargs):
    if isinstance(data, str):
        try:
            data = _json.loads(data)
        except Exception:
            return Html(f'<pre style="color:var(--nb-text,#fafafa);font-size:13px;">{data}</pre>')
    body = _render_tree_node(data)
    html = (
        f'<div class="chani-json" '
        f'style="font-family:monospace;padding:8px 12px;border:1px solid var(--nb-border,#27272a);border-radius:8px;">'
        f'{body}</div>'
    )
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/lazy.py': `from marimo._output.html import Html

def lazy(item, **kwargs):
    if hasattr(item, '_repr_html_'):
        inner = item._repr_html_()
    else:
        inner = str(item)
    return Html(inner)
`,

'/lib/python3.12/marimo/_layout/plain.py': `from marimo._output.html import Html

def plain(item, **kwargs):
    if hasattr(item, '_repr_html_'):
        inner = item._repr_html_()
    else:
        inner = str(item)
    return Html(inner)
`,

'/lib/python3.12/marimo/_layout/stacks.py': `from marimo._output.html import Html

def _render_item(item):
    if hasattr(item, '_repr_html_'):
        return item._repr_html_()
    return f'<span>{str(item)}</span>'

def hstack(items, gap=0.5, justify='start', align='center', widths='equal', **kwargs):
    inner = ''.join(f'<div class="chani-stack-item">{_render_item(it)}</div>' for it in items)
    style = f'display:flex;flex-direction:row;gap:{gap}rem;justify-content:{justify};align-items:{align};'
    html = f'<div class="chani-hstack" style="{style}">{inner}</div>'
    return Html(html)

def vstack(items, gap=0.5, justify='start', align='stretch', **kwargs):
    inner = ''.join(f'<div class="chani-stack-item">{_render_item(it)}</div>' for it in items)
    style = f'display:flex;flex-direction:column;gap:{gap}rem;justify-content:{justify};align-items:{align};'
    html = f'<div class="chani-vstack" style="{style}">{inner}</div>'
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/stat.py': `from marimo._output.html import Html

def stat(value, label=None, caption=None, direction=None,
         bordered=False, target_direction='increase', slot=None, **kwargs):
    parts = []

    if label:
        parts.append(f'<div style="font-size:12px;color:var(--nb-text-muted,#71717a);margin-bottom:2px;">{label}</div>')

    val_style = 'font-size:28px;font-weight:700;color:var(--nb-text,#fafafa);line-height:1.2;'
    arrow = ''
    if direction:
        is_positive = (direction == target_direction) if target_direction else True
        color = 'var(--nb-stat-positive,#22c55e)' if is_positive else 'var(--nb-stat-negative,#ef4444)'
        symbol = '\\u2191' if direction == 'increase' else '\\u2193'
        arrow = f'<span style="color:{color};font-size:18px;margin-left:6px;">{symbol}</span>'

    parts.append(f'<div style="{val_style}">{value}{arrow}</div>')

    if caption:
        cap_style = 'font-size:12px;color:var(--nb-text-muted,#71717a);margin-top:2px;'
        if direction:
            is_positive = (direction == target_direction) if target_direction else True
            cap_color = 'var(--nb-stat-positive,#22c55e)' if is_positive else 'var(--nb-stat-negative,#ef4444)'
            cap_style += f'color:{cap_color};'
        parts.append(f'<div style="{cap_style}">{caption}</div>')

    content = ''.join(parts)

    if slot and hasattr(slot, '_repr_html_'):
        slot_html = slot._repr_html_()
        content = f'<div style="display:flex;align-items:center;gap:12px;"><div>{content}</div><div>{slot_html}</div></div>'

    border_style = 'border:1px solid var(--nb-border,#27272a);' if bordered else ''
    container_style = f'padding:16px;border-radius:8px;{border_style}'

    html = f'<div class="chani-stat" style="{container_style}">{content}</div>'
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/tabs.py': `from marimo._output.html import Html

def tabs(tab_dict, **kwargs):
    if not isinstance(tab_dict, dict):
        return Html('<div>Invalid tabs data</div>')
    tab_id = f"tabs_{id(tab_dict)}"
    headers = []
    panels = []
    for i, (label, content) in enumerate(tab_dict.items()):
        active = ' active' if i == 0 else ''
        display = 'block' if i == 0 else 'none'
        if hasattr(content, '_repr_html_'):
            inner = content._repr_html_()
        else:
            inner = str(content)
        js = (
            f"document.querySelectorAll('#{tab_id} .chani-tab-panel').forEach(p=>p.style.display='none');"
            f"document.querySelectorAll('#{tab_id} .chani-tab-btn').forEach(b=>b.classList.remove('active'));"
            f"this.classList.add('active');"
            f"document.getElementById('{tab_id}_p{i}').style.display='block'"
        )
        headers.append(f'<button class="chani-tab-btn{active}" onclick="{js}">{label}</button>')
        panels.append(f'<div id="{tab_id}_p{i}" class="chani-tab-panel" style="display:{display}">{inner}</div>')
    html = (
        f'<div id="{tab_id}" class="chani-tabs">'
        f'<div class="chani-tab-bar">{"".join(headers)}</div>'
        f'<div class="chani-tab-panels">{"".join(panels)}</div>'
        f'</div>'
    )
    return Html(html)
`,

'/lib/python3.12/marimo/_layout/tree.py': `from marimo._output.html import Html

def _render_tree_node(data, depth=0):
    if isinstance(data, dict):
        items = []
        for k, v in data.items():
            child = _render_tree_node(v, depth + 1)
            items.append(
                f'<details class="chani-tree-node" {"open" if depth < 2 else ""}>'
                f'<summary style="cursor:pointer;padding:2px 0;color:var(--nb-text,#fafafa);font-size:13px;">'
                f'<span style="color:var(--nb-text-muted,#71717a);">{k}</span></summary>'
                f'<div style="margin-left:16px;border-left:1px solid var(--nb-border,#27272a);padding-left:8px;">{child}</div>'
                f'</details>'
            )
        return ''.join(items)
    elif isinstance(data, (list, tuple)):
        items = []
        for i, v in enumerate(data):
            child = _render_tree_node(v, depth + 1)
            items.append(
                f'<details class="chani-tree-node" {"open" if depth < 2 else ""}>'
                f'<summary style="cursor:pointer;padding:2px 0;color:var(--nb-text,#fafafa);font-size:13px;">'
                f'<span style="color:var(--nb-text-muted,#71717a);">[{i}]</span></summary>'
                f'<div style="margin-left:16px;border-left:1px solid var(--nb-border,#27272a);padding-left:8px;">{child}</div>'
                f'</details>'
            )
        return ''.join(items)
    elif hasattr(data, '_repr_html_'):
        return data._repr_html_()
    else:
        val = str(data)
        return f'<span style="color:var(--nb-text-secondary,#a1a1aa);font-size:13px;">{val}</span>'

def tree(data, label=None, **kwargs):
    header = ''
    if label:
        header = f'<div style="font-weight:600;font-size:13px;color:var(--nb-text,#fafafa);margin-bottom:4px;">{label}</div>'
    body = _render_tree_node(data)
    html = (
        f'<div class="chani-tree" '
        f'style="font-family:monospace;padding:8px 12px;border:1px solid var(--nb-border,#27272a);border-radius:8px;">'
        f'{header}{body}</div>'
    )
    return Html(html)
`,

'/lib/python3.12/marimo/_output/__init__.py': ``,

'/lib/python3.12/marimo/_output/display.py': `from marimo._output.html import Html

def as_html(obj):
    if hasattr(obj, '_repr_html_'):
        return Html(obj._repr_html_())
    return Html(f'<pre>{repr(obj)}</pre>')
`,

'/lib/python3.12/marimo/_output/html.py': `class Html:
    def __init__(self, text=''):
        self._text = str(text)

    def _repr_html_(self):
        return self._text

    def __str__(self):
        return self._text

    def __format__(self, spec):
        return self._text

    def __repr__(self):
        return f"Html({self._text[:50]!r}...)" if len(self._text) > 50 else f"Html({self._text!r})"

    def batch(self, **kwargs):
        from marimo._ui.base import UIElement
        html = self._text
        widget_ids = []
        for key, widget in kwargs.items():
            if isinstance(widget, UIElement):
                placeholder = '{' + key + '}'
                html = html.replace(placeholder, widget._repr_html_())
                widget_ids.append(widget._id)
        result = Html(html)
        result._widget_ids = widget_ids
        return result
`,

'/lib/python3.12/marimo/_output/md.py': `from marimo._output.html import Html

def md(text):
    try:
        import markdown as _md
        html = _md.markdown(str(text), extensions=['tables', 'fenced_code'])
    except ImportError:
        html = '<p>' + str(text).replace('\\n', '<br>') + '</p>'
    return Html(html)
`,

'/lib/python3.12/marimo/_output/media.py': `from marimo._output.html import Html

def image(src, alt='', width=None, height=None, **kwargs):
    style = ''
    if width:
        style += f'max-width:{width}px;'
    if height:
        style += f'max-height:{height}px;'
    return Html(f'<img src="{src}" alt="{alt}" style="{style}" />')

def video(src, **kwargs):
    return Html(f'<video src="{src}" controls></video>')

def audio(src, **kwargs):
    return Html(f'<audio src="{src}" controls></audio>')
`,

'/lib/python3.12/marimo/_state.py': `class _StateGetter:
    def __init__(self, state_obj):
        self._state = state_obj
    def __call__(self):
        return self._state._value
    def __repr__(self):
        return f"StateGetter(value={self._state._value!r})"

class _StateSetter:
    def __init__(self, state_obj):
        self._state = state_obj
    def __call__(self, value):
        self._state._value = value
    def __repr__(self):
        return f"StateSetter()"

class _State:
    def __init__(self, initial_value):
        self._value = initial_value

def state(initial_value):
    s = _State(initial_value)
    return (_StateGetter(s), _StateSetter(s))
`,

'/lib/python3.12/marimo/_ui/__init__.py': `from marimo._ui.slider import slider
from marimo._ui.dropdown import dropdown
from marimo._ui.text import text, text_area
from marimo._ui.number import number
from marimo._ui.checkbox import checkbox
from marimo._ui.switch import switch
from marimo._ui.radio import radio
from marimo._ui.button import button, run_button
from marimo._ui.date import date
from marimo._ui.multiselect import multiselect
from marimo._ui.range_slider import range_slider
from marimo._ui.table import table
from marimo._ui.file import file
from marimo._ui.code_editor import code_editor
from marimo._ui.form import form
from marimo._ui.dictionary import dictionary
from marimo._ui.array import array
from marimo._ui.batch import batch
`,

'/lib/python3.12/marimo/_ui/array.py': `from marimo._ui.base import UIElement

def array(elements, label=None, **kwargs):
    items = []
    if isinstance(elements, (list, tuple)):
        for widget in elements:
            if isinstance(widget, UIElement):
                items.append(widget._to_json())
            else:
                items.append({"type": "static", "value": str(widget)})
    return UIElement("array",
        items=items, label=label,
        value=[w._value if isinstance(w, UIElement) else None
               for w in (elements if isinstance(elements, (list, tuple)) else [])])
`,

'/lib/python3.12/marimo/_ui/base.py': `import json

class UIElement:
    _registry = {}
    _next_id = 0
    _on_change_callback = None

    def __init__(self, widget_type, **kwargs):
        UIElement._next_id += 1
        self._id = f"w{UIElement._next_id}"
        self._type = widget_type
        self._config = {}
        for k, v in kwargs.items():
            if k != 'value':
                self._config[k] = v
        self._value = kwargs.get('value')
        self._initial_value = self._value
        UIElement._registry[self._id] = self

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, new_val):
        self._value = new_val

    def _to_json(self):
        cfg = {}
        for k, v in self._config.items():
            try:
                json.dumps(v)
                cfg[k] = v
            except (TypeError, ValueError):
                cfg[k] = str(v)
        return {
            "__chani_widget__": True,
            "id": self._id,
            "type": self._type,
            "config": cfg,
            "value": self._value
        }

    def _repr_html_(self):
        data = json.dumps(self._to_json())
        return f'<chani-widget data-widget-id="{self._id}">{data}</chani-widget>'

    def __repr__(self):
        return f"mo.ui.{self._type}(value={self._value!r})"

    def __str__(self):
        return self._repr_html_()

    def __format__(self, spec):
        return self._repr_html_()

    @classmethod
    def _get_widget(cls, widget_id):
        return cls._registry.get(widget_id)

    @classmethod
    def _set_value(cls, widget_id, value):
        w = cls._registry.get(widget_id)
        if w:
            w._value = value
            return True
        return False

    @classmethod
    def _get_all_widgets(cls):
        return {wid: w._to_json() for wid, w in cls._registry.items()}

    @classmethod
    def _reset(cls):
        cls._registry.clear()
        cls._next_id = 0
`,

'/lib/python3.12/marimo/_ui/batch.py': `from marimo._ui.base import UIElement
from marimo._output.html import Html

def batch(html_template, **elements):
    if isinstance(html_template, Html):
        html_str = html_template._text
    else:
        html_str = str(html_template)
    items = {}
    for key, widget in elements.items():
        if isinstance(widget, UIElement):
            items[key] = widget._to_json()
            html_str = html_str.replace('{' + key + '}', widget._repr_html_())
    result = UIElement("batch",
        html=html_str, items=items,
        value={k: w._value if isinstance(w, UIElement) else None
               for k, w in elements.items()})
    return result
`,

'/lib/python3.12/marimo/_ui/button.py': `from marimo._ui.base import UIElement

def button(value=None, label='Click', kind='primary', on_click=None, **kwargs):
    if value is None:
        value = 0
    return UIElement("button",
        value=value, label=label, kind=kind)

def run_button(label='Run', **kwargs):
    return UIElement("run_button", value=False, label=label)
`,

'/lib/python3.12/marimo/_ui/checkbox.py': `from marimo._ui.base import UIElement

def checkbox(value=False, label='', **kwargs):
    return UIElement("checkbox", value=value, label=label)
`,

'/lib/python3.12/marimo/_ui/code_editor.py': `from marimo._ui.base import UIElement

def code_editor(value='', language='python', label=None, **kwargs):
    return UIElement("code_editor",
        value=value, language=language, label=label)
`,

'/lib/python3.12/marimo/_ui/date.py': `from marimo._ui.base import UIElement

def date(value=None, label=None, **kwargs):
    return UIElement("date", value=value or '', label=label)
`,

'/lib/python3.12/marimo/_ui/dictionary.py': `from marimo._ui.base import UIElement

def dictionary(elements, label=None, **kwargs):
    items = {}
    if isinstance(elements, dict):
        for key, widget in elements.items():
            if isinstance(widget, UIElement):
                items[key] = widget._to_json()
            else:
                items[key] = {"type": "static", "value": str(widget)}
    return UIElement("dictionary",
        items=items, label=label,
        value={k: w._value if isinstance(w, UIElement) else None
               for k, w in (elements if isinstance(elements, dict) else {}).items()})
`,

'/lib/python3.12/marimo/_ui/dropdown.py': `from marimo._ui.base import UIElement

def dropdown(options=None, value=None, label=None, full_width=False, **kwargs):
    if options is None:
        options = []
    if isinstance(options, dict):
        opt_list = list(options.keys())
    else:
        opt_list = list(options)
    if value is None and opt_list:
        value = opt_list[0]
    return UIElement("dropdown",
        options=opt_list, value=value,
        label=label, full_width=full_width)
`,

'/lib/python3.12/marimo/_ui/file.py': `from marimo._ui.base import UIElement

def file(filetypes=None, multiple=False, label=None, **kwargs):
    if filetypes is None:
        filetypes = []
    return UIElement("file",
        filetypes=filetypes, multiple=multiple,
        label=label, value=None)
`,

'/lib/python3.12/marimo/_ui/form.py': `from marimo._ui.base import UIElement

def form(element, submit_button_label='Submit', label=None, **kwargs):
    inner_json = None
    if isinstance(element, UIElement):
        inner_json = element._to_json()
    return UIElement("form",
        inner=inner_json,
        submit_button_label=submit_button_label,
        label=label,
        value=None)
`,

'/lib/python3.12/marimo/_ui/multiselect.py': `from marimo._ui.base import UIElement

def multiselect(options=None, value=None, label=None, full_width=False, **kwargs):
    if options is None:
        options = []
    if isinstance(options, dict):
        opt_list = list(options.keys())
    else:
        opt_list = list(options)
    if value is None:
        value = []
    return UIElement("multiselect",
        options=opt_list, value=value,
        label=label, full_width=full_width)
`,

'/lib/python3.12/marimo/_ui/number.py': `from marimo._ui.base import UIElement

def number(start=None, stop=None, step=1, value=None, label=None, full_width=False, **kwargs):
    if value is None:
        value = start if start is not None else 0
    return UIElement("number",
        start=start, stop=stop, step=step, value=value,
        label=label, full_width=full_width)
`,

'/lib/python3.12/marimo/_ui/radio.py': `from marimo._ui.base import UIElement

def radio(options=None, value=None, label=None, **kwargs):
    if options is None:
        options = []
    if isinstance(options, dict):
        opt_list = list(options.keys())
    else:
        opt_list = list(options)
    if value is None and opt_list:
        value = opt_list[0]
    return UIElement("radio",
        options=opt_list, value=value, label=label)
`,

'/lib/python3.12/marimo/_ui/range_slider.py': `from marimo._ui.base import UIElement

def range_slider(start=0, stop=100, step=1, value=None, label=None, full_width=False, **kwargs):
    if value is None:
        value = [start, stop]
    return UIElement("range_slider",
        start=start, stop=stop, step=step, value=value,
        label=label, full_width=full_width)
`,

'/lib/python3.12/marimo/_ui/slider.py': `from marimo._ui.base import UIElement

def slider(start=0, stop=100, step=1, value=None, label=None, full_width=False, **kwargs):
    if value is None:
        value = start
    return UIElement("slider",
        start=start, stop=stop, step=step, value=value,
        label=label, full_width=full_width)
`,

'/lib/python3.12/marimo/_ui/switch.py': `from marimo._ui.base import UIElement

def switch(value=False, label='', **kwargs):
    return UIElement("switch", value=value, label=label)
`,

'/lib/python3.12/marimo/_ui/table.py': `from marimo._ui.base import UIElement
import json

def table(data, selection=None, label=None, page_size=10, **kwargs):
    if selection is None:
        selection = 'single'
    rows = []
    columns = []
    if isinstance(data, list) and len(data) > 0:
        if isinstance(data[0], dict):
            columns = list(data[0].keys())
            rows = data
        else:
            columns = [f"col_{i}" for i in range(len(data[0]))]
            rows = [{c: v for c, v in zip(columns, row)} for row in data]
    elif hasattr(data, 'to_dict'):
        try:
            records = data.head(500).to_dict(orient='records')
            columns = [str(c) for c in data.columns]
            rows = records
        except:
            pass
    serializable_rows = []
    for row in rows:
        sr = {}
        for k, v in row.items():
            try:
                json.dumps(v)
                sr[str(k)] = v
            except (TypeError, ValueError):
                sr[str(k)] = str(v)
        serializable_rows.append(sr)
    return UIElement("table",
        columns=columns, rows=serializable_rows,
        selection=selection, label=label, page_size=page_size,
        value=[])
`,

'/lib/python3.12/marimo/_ui/text.py': `from marimo._ui.base import UIElement

def text(value='', label=None, placeholder=None, full_width=False, **kwargs):
    return UIElement("text",
        value=value, label=label, placeholder=placeholder,
        full_width=full_width)

def text_area(value='', label=None, placeholder=None, full_width=False, **kwargs):
    return UIElement("text_area",
        value=value, label=label, placeholder=placeholder,
        full_width=full_width)
`,

};
