"""DartLab Unified Data Workbench public package."""

from dartlab.dataHub.contracts import (
    AssetRef,
    CatalogQuery,
    DataAssetDescriptor,
    DataCatalogResult,
    DataGap,
    DataLineage,
    DataPartition,
    DataQuery,
    DataRequest,
    DataResult,
    FactorProjection,
    GraphProjection,
    NarrativeProjection,
    NativeProjection,
    QualityAssertion,
    QueryBudget,
    RecordsProjection,
    ResourceProjection,
    TimeContext,
    UniverseCoverage,
    UniverseSelection,
)
from dartlab.dataHub.controlPlane import DataHubControlError, DataHubJob
from dartlab.dataHub.entry import Data, DataHub, data, dataHub
from dartlab.dataHub.featureObservation import (
    FeatureObservationError,
    VariableObservation,
    makeVariableObservation,
    validateVariableObservation,
)
from dartlab.dataHub.featureQuery import (
    FeatureObservationSet,
    FeatureQueryError,
    FeatureReadQuery,
    FeatureReadResult,
    FeatureSelection,
    buildFeatureObservationSet,
    featureObservationSetFromValue,
    readFeatures,
)
from dartlab.dataHub.featureRegistry import (
    StateVariableError,
    StateVariableRegistry,
    StateVariableSpec,
    buildStateVariableRegistry,
    stateVariableContractHash,
)
from dartlab.dataHub.materialization import (
    MaterializationDirective,
    MaterializationReceipt,
)
from dartlab.dataHub.pageScan import (
    PageScanCheckpoint,
    PageScanError,
    iterDataArrowBatches,
    iterDataResultPages,
)
from dartlab.dataHub.remote import AsyncDataHubClient, DataHubClient
from dartlab.dataHub.vintage import VintageError, VintageRef, isExactAsKnown, validateVintageRef
from dartlab.dataHub.workerPlane import DataHubWorker, WorkerRun

__all__ = [
    "AssetRef",
    "AsyncDataHubClient",
    "CatalogQuery",
    "Data",
    "DataHub",
    "DataHubClient",
    "DataHubControlError",
    "DataHubJob",
    "DataHubWorker",
    "DataAssetDescriptor",
    "DataCatalogResult",
    "DataGap",
    "DataLineage",
    "DataPartition",
    "DataQuery",
    "DataRequest",
    "DataResult",
    "FactorProjection",
    "FeatureObservationError",
    "FeatureObservationSet",
    "FeatureQueryError",
    "FeatureReadQuery",
    "FeatureReadResult",
    "FeatureSelection",
    "GraphProjection",
    "MaterializationDirective",
    "MaterializationReceipt",
    "NarrativeProjection",
    "NativeProjection",
    "PageScanCheckpoint",
    "PageScanError",
    "QueryBudget",
    "QualityAssertion",
    "RecordsProjection",
    "ResourceProjection",
    "StateVariableError",
    "StateVariableRegistry",
    "StateVariableSpec",
    "TimeContext",
    "UniverseCoverage",
    "UniverseSelection",
    "VariableObservation",
    "VintageError",
    "VintageRef",
    "WorkerRun",
    "buildFeatureObservationSet",
    "buildStateVariableRegistry",
    "data",
    "dataHub",
    "featureObservationSetFromValue",
    "isExactAsKnown",
    "iterDataArrowBatches",
    "iterDataResultPages",
    "makeVariableObservation",
    "readFeatures",
    "stateVariableContractHash",
    "validateVariableObservation",
    "validateVintageRef",
]
