#!/usr/bin/env python3
"""Block generated-attribution markers in commit messages and staged content."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

BANNED_PATTERNS = [
    r"co-authored-by",
    r"generated by\s+(chatgpt|claude|codex|gpt|gemini|llm|ai)",
    r"ai assisted",
    r"ai-generated",
    r"ai generated",
    r"with claude",
    r"with chatgpt",
    r"with codex",
    r"gpt 협업",
]

COMPILED_PATTERNS = [re.compile(pattern, re.IGNORECASE) for pattern in BANNED_PATTERNS]

# 비전문적·비중립·욕설 표현 — 공개 artifact 인 커밋 메시지에 원천 금지(주체 중립 정책).
# 커밋 메시지 전용: 스테이징 내용/히스토리 일반 스캔에는 미적용(테스트 픽스처·데이터 오탐 방지).
# 정상 한국어 단어에 박혀 오탐 나는 표현(예: '전망했다'의 '망했')은 의도적으로 제외.
UNPROFESSIONAL_PATTERNS = [
    r"쓰레기",
    r"병신",
    r"미친",
    r"멍청",
    r"바보",
    r"엉망",
    r"개판",
    r"짜증",
    r"존나",
    r"씨발",
    r"좆",
    r"닥쳐",
    r"꺼져",
    r"\bshit\b",
    r"\bfuck",
    r"\bdamn\b",
    r"\bcrap\b",
    r"\bwtf\b",
    r"\bstupid\b",
    r"\bidiot\b",
    r"\bdumb(ass)?\b",
]

COMMIT_MESSAGE_BANNED_PATTERNS = [
    *BANNED_PATTERNS,
    r"\b(chatgpt|claude|codex|gpt|gemini|llm|ai)\b",
    r"생성\s*도구",
    r"작성\s*도구",
    r"모델\s*작성",
    *UNPROFESSIONAL_PATTERNS,
]
COMPILED_COMMIT_MESSAGE_PATTERNS = [re.compile(pattern, re.IGNORECASE) for pattern in COMMIT_MESSAGE_BANNED_PATTERNS]
COMMIT_TYPES = (
    "추가",
    "수정",
    "개선",
    "변경",
    "삭제",
    "정리",
    "문서",
    "테스트",
    "빌드",
    "릴리즈",
    "보안",
    "성능",
    "리팩터",
    "리팩토링",
    "복구",
    "설정",
    "검증",
)
GENERIC_COMMIT_DETAILS = {
    "작업",
    "수정",
    "변경",
    "업데이트",
    "정리",
    "개선",
    "추가",
    "삭제",
    "wip",
    "fix",
    "update",
    "changes",
}
HANGUL_RE = re.compile(r"[가-힣]")
ZERO_SHA = "0" * 40


def runGit(args: list[str], check: bool = True) -> str:
    proc = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout or ""


def findMatches(text: str) -> list[str]:
    if not text:
        return []
    matches: list[str] = []
    seen: set[str] = set()
    for pattern in COMPILED_PATTERNS:
        for match in pattern.finditer(text):
            snippet = match.group(0)
            key = snippet.lower()
            if key not in seen:
                seen.add(key)
                matches.append(snippet)
    return matches


def findCommitMessageMatches(text: str) -> list[str]:
    if not text:
        return []
    matches: list[str] = []
    seen: set[str] = set()
    for pattern in COMPILED_COMMIT_MESSAGE_PATTERNS:
        for match in pattern.finditer(text):
            snippet = match.group(0)
            key = snippet.lower()
            if key not in seen:
                seen.add(key)
                matches.append(snippet)
    return matches


def reportFailure(title: str, details: list[str]) -> int:
    print(f"[ai-policy] {title}", file=sys.stderr)
    for detail in details:
        print(f"  - {detail}", file=sys.stderr)
    return 1


def checkText(label: str, text: str) -> int:
    matches = findMatches(text)
    if not matches:
        return 0
    return reportFailure(label, [f"금지 패턴 발견: {', '.join(matches)}"])


def checkCommitMessage(path: str) -> int:
    content = Path(path).read_text(encoding="utf-8", errors="replace")
    failures: list[str] = []
    matches = findCommitMessageMatches(content)
    if matches:
        failures.append(f"금지 패턴 발견: {', '.join(matches)}")

    subject = next(
        (
            line.strip().lstrip("\ufeff")
            for line in content.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ),
        "",
    )
    if not subject:
        failures.append("커밋 제목이 비어 있습니다.")
    elif not HANGUL_RE.search(subject):
        failures.append("커밋 제목은 한글로 작성해야 합니다.")
    elif ":" not in subject:
        failures.append("커밋 제목은 '성격: 변경 내용' 형식이어야 합니다.")
    else:
        commitType, detail = subject.split(":", 1)
        commitType = commitType.strip()
        detail = detail.strip()
        if commitType not in COMMIT_TYPES:
            failures.append(f"커밋 성격은 다음 중 하나여야 합니다: {', '.join(COMMIT_TYPES)}")
        if not detail:
            failures.append("커밋 제목에 실제 변경 내용을 적어야 합니다.")
        elif len(detail) < 6 or detail.lower() in GENERIC_COMMIT_DETAILS:
            failures.append("커밋 제목의 변경 내용이 너무 짧거나 일반적입니다.")
        elif not HANGUL_RE.search(detail):
            failures.append("커밋 제목의 변경 내용은 한글 설명을 포함해야 합니다.")

    if not failures:
        return 0
    return reportFailure("커밋 메시지 규칙을 위반했습니다.", failures)


def stagedFiles() -> list[str]:
    output = runGit(["diff", "--cached", "--name-only", "--diff-filter=ACMR"])
    return [line for line in output.splitlines() if line.strip()]


def checkStaged() -> int:
    failures: list[str] = []
    for filePath in stagedFiles():
        if filePath == "tests/audit/commitPolicy.py":
            continue
        if Path(filePath).suffix.lower() == ".parquet":
            continue
        try:
            content = runGit(["show", f":{filePath}"])
        except RuntimeError:
            continue
        matches = findMatches(content)
        if matches:
            failures.append(f"{filePath}: {', '.join(matches)}")
    if not failures:
        return 0
    return reportFailure("스테이징된 내용에 AI 흔적이 포함되어 있습니다.", failures)


def commitRange(base: str | None, head: str) -> list[str]:
    if base and base != ZERO_SHA:
        revspec = f"{base}..{head}"
        output = runGit(["rev-list", revspec])
        return [line for line in output.splitlines() if line.strip()]
    output = runGit(["rev-list", head, "--not", "--all"])
    commits = [line for line in output.splitlines() if line.strip()]
    return commits or [head]


def checkCommitRange(base: str | None, head: str) -> int:
    failures: list[str] = []
    for commit in commitRange(base, head):
        message = runGit(["log", "--format=%B", "-n", "1", commit])
        matches = findMatches(message)
        if matches:
            failures.append(f"{commit[:12]}: {', '.join(matches)}")
    if not failures:
        return 0
    return reportFailure("커밋 히스토리에 AI 기여자 흔적이 포함되어 있습니다.", failures)


def changedFilesInRange(base: str | None, head: str) -> list[str]:
    if base and base != ZERO_SHA:
        output = runGit(["diff", "--name-only", f"{base}..{head}", "--diff-filter=ACMR"])
        return [line for line in output.splitlines() if line.strip()]
    files: set[str] = set()
    for commit in commitRange(base, head):
        output = runGit(["diff-tree", "--no-commit-id", "--name-only", "-r", "--diff-filter=ACMR", commit])
        for line in output.splitlines():
            if line.strip():
                files.add(line)
    return sorted(files)


def checkFilesInRange(base: str | None, head: str) -> int:
    failures: list[str] = []
    for filePath in changedFilesInRange(base, head):
        if filePath == "tests/audit/commitPolicy.py":
            continue
        if Path(filePath).suffix.lower() == ".parquet":
            continue
        try:
            content = runGit(["show", f"{head}:{filePath}"])
        except RuntimeError as exc:
            failures.append(f"{filePath}: {exc}")
            continue
        matches = findMatches(content)
        if matches:
            failures.append(f"{filePath}: {', '.join(matches)}")
    if not failures:
        return 0
    return reportFailure("변경 파일 내용에 AI 흔적이 포함되어 있습니다.", failures)


def checkPush() -> int:
    failures = 0
    for line in sys.stdin:
        if not line.strip():
            continue
        localRef, localSha, remoteRef, remoteSha = line.strip().split()
        if localSha == ZERO_SHA:
            continue
        if checkCommitRange(remoteSha, localSha) != 0:
            failures = 1
        if checkFilesInRange(remoteSha, localSha) != 0:
            failures = 1
    return failures


def buildParser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-commit-msg", dest="checkCommitMsg")
    parser.add_argument("--check-staged", dest="checkStaged", action="store_true")
    parser.add_argument("--check-range", dest="checkRange", nargs=2, metavar=("BASE", "HEAD"))
    parser.add_argument("--check-push", dest="checkPush", action="store_true")
    return parser


def main() -> int:
    args = buildParser().parse_args()
    if args.checkCommitMsg:
        return checkCommitMessage(args.checkCommitMsg)
    if args.checkStaged:
        return checkStaged()
    if args.checkRange:
        base, head = args.checkRange
        commitStatus = checkCommitRange(base, head)
        fileStatus = checkFilesInRange(base, head)
        return 1 if commitStatus or fileStatus else 0
    if args.checkPush:
        return checkPush()
    print("No check mode provided.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
