"""Resource multiplex paging lane 파사드.

이 패키지의 진입면을 한곳에 모은다. 아래 이름들은 본문에서 쓰지 않으므로 자동 도구가
미사용 import 로 오판하기 쉽다. 걷어내면 소비자와 동적 참조가 깨지므로 `__all__` 로
명시 고정한다.
"""

from __future__ import annotations

from .api import (
    executeInitialResourcePaging,
    resumeResourcePaging,
)
from .models import (
    _CURSOR_KEYS,
    _FORMAT_VERSION,
    _MAX_PAGE_SHARDS,
    _MULTIPLEX_METADATA,
    _MULTIPLEX_SCHEMA,
    _OWNER_CONTRACTS_MODULE,
    _OWNER_MODULE,
    _PAGEABLE_PARAM_KEYS,
    _REQUEST_MAPPING_KEYS,
    _SESSION_KEYS,
    _TASK_KEYS,
    _DecodedMultiplex,
    _MultiplexEntry,
    _OwnerBoundary,
    _ResourceSession,
    _ResourceTask,
    _textDigest,
)
from .payload import (
    _decodeMultiplex,
    _encodeMultiplex,
    _innerTable,
    _validateMultiplexPayload,
)
from .results import (
    _failedResult,
    _planFailure,
    _resultFromPage,
    _universeCoverage,
)
from .schedule import (
    _materialize,
    _materializeOnce,
    _progressSelector,
    _progressValues,
)
from .source import (
    _continuationStore,
    _contractDigest,
    _currentSourcePins,
    _descriptionTask,
    _normalizedRequestMapping,
    _ownerBoundary,
    _pins,
    _preparedDescriptionTask,
    _requireCurrentPins,
    _validateOwnerPage,
    isPageableResource,
)
from .state import (
    _cursorBytes,
    _cursorFromBytes,
    _cursorMapping,
    _cursorPosition,
    _decodeSession,
    _decodeTask,
    _decodeTaskCursor,
    _encodeSession,
    _jsonLoad,
    _originCursor,
    _queryPayload,
    _requireDigest,
    _requireText,
    _strictTree,
    _taskTree,
    _validateQueryPayload,
)

__all__ = [
    "_CURSOR_KEYS",
    "_DecodedMultiplex",
    "_FORMAT_VERSION",
    "_MAX_PAGE_SHARDS",
    "_MULTIPLEX_METADATA",
    "_MULTIPLEX_SCHEMA",
    "_MultiplexEntry",
    "_OWNER_CONTRACTS_MODULE",
    "_OWNER_MODULE",
    "_OwnerBoundary",
    "_PAGEABLE_PARAM_KEYS",
    "_REQUEST_MAPPING_KEYS",
    "_ResourceSession",
    "_ResourceTask",
    "_SESSION_KEYS",
    "_TASK_KEYS",
    "_continuationStore",
    "_contractDigest",
    "_currentSourcePins",
    "_cursorBytes",
    "_cursorFromBytes",
    "_cursorMapping",
    "_cursorPosition",
    "_decodeMultiplex",
    "_decodeSession",
    "_decodeTask",
    "_decodeTaskCursor",
    "_descriptionTask",
    "_encodeMultiplex",
    "_encodeSession",
    "_failedResult",
    "_innerTable",
    "_jsonLoad",
    "_materialize",
    "_materializeOnce",
    "_normalizedRequestMapping",
    "_originCursor",
    "_ownerBoundary",
    "_pins",
    "_planFailure",
    "_preparedDescriptionTask",
    "_progressSelector",
    "_progressValues",
    "_queryPayload",
    "_requireCurrentPins",
    "_requireDigest",
    "_requireText",
    "_resultFromPage",
    "_strictTree",
    "_taskTree",
    "_textDigest",
    "_universeCoverage",
    "_validateMultiplexPayload",
    "_validateOwnerPage",
    "_validateQueryPayload",
    "executeInitialResourcePaging",
    "isPageableResource",
    "resumeResourcePaging",
]
