"""Batch 24: Learn 255 unmapped accounts from 128 2-unmapped stocks"""

import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[5]))

import json

from core.dart.searchDart.finance.v7.synonymLearner import SynonymLearner

learner = SynonymLearner()

p = Path(__file__).parent.parent / "standardAccounts.json"
with open(str(p), "r", encoding="utf-8") as f:
    standards = json.load(f)
allSnakeIds = set(a["snakeId"] for a in standards["accounts"] if a.get("snakeId"))

mapping = {
    "(1)영업활동으로부터창출된현금흐름": "cash_flows_from_operatings",
    "(2)당기순이익(손실)조정을위한가감": "other_adjustments_for_noncash_incomeexpense",
    "(3)영업활동으로인한자산·부채의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "(3)운전자본의조정": "change_in_working_capital",
    "1)영업에서창출된현금흐름": "cash_flows_from_operatings",
    "영업으로부터사용된현금": "cash_flows_from_operatings",
    "비현금흐름의조정": "other_adjustments_for_noncash_incomeexpense",
    "당기순이익(조정)": "other_adjustments_for_noncash_incomeexpense",
    "현금성자산에대한환율효과": "difference_by_changes_in_foreign_exchange_rates",
    "현금성자산의환율변동": "difference_by_changes_in_foreign_exchange_rates",
    "외화표시현금및현금서성자산의환율변동효과": "difference_by_changes_in_foreign_exchange_rates",
    "복구비의지출": "provisions_for_restoration_costs",
    "복구의무이행": "provisions_for_restoration_costs",
    "복구충당부채의상환": "provisions_for_restoration_costs",
    "단기제품보증충당부채의증가(감소)": "product_warranties_provisions",
    "총당부채": "longterm_provisions",
    "판매보증충담금전입액": "product_warranties_provisions",
    "판보충전입액": "product_warranties_provisions",
    "기타포괄-공정가치금융평가손실(이익)": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄-공정가치측정자산평가손실": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄-공정가치측정평가손실": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익-공정가치금융자산의재측정요소": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익-공정가치금융자산의처분": "gains_on_disposition_of_availableforsale_financial_assets",
    "기타포괄손익-공정가치금융자산평가손익대체": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익-공정가치측정귬융자산의증가": "increase_in_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익-공정가치측정금융가산의증가": "increase_in_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익_공정가치측정지분상품": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익공정가치측정금융상품처분으로인한재분류": "gains_on_disposition_of_availableforsale_financial_assets",
    "기타포괄손익투계액": "accumulated_other_comprehensive_income",
    "기타포괄손인공정가치측정금융자산의감소": "decrease_in_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "총기타포괄이익": "total_comprehensive_income",
    "기타포괄손익관련법인세효과": "income_taxes_effects",
    "매도가능금융자산과관련된법인세": "income_taxes_effects",
    "법인세효과": "income_taxes_effects",
    "공정가치측금융자산(유동)": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손공정가치측정금융자산의취득": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익-공장가치측정금융자산의취득": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익인식금융자산의처분이익": "gains_on_disposition_of_financial_assets",
    "당기손익인식지정금융자산": "designatedfinancial_assets_at_fv_through_profit",
    "공정가치측정지분상품처분에따른이익잉여금대체": "gains_on_disposition_of_financial_assets",
    "매도가능금융자산평가손익변동": "gains_on_valuation_of_availableforsale_financial_assets",
    "매도금융자산처분으로인한재분류": "gains_on_disposition_of_availableforsale_financial_assets",
    "매도금융자산평가손익": "gains_on_valuation_of_availableforsale_financial_assets",
    "당기손익으로재분류되지않는세후기타포괄손익의법인세": "income_taxes_effects",
    "임차보증금지급": "leasehold_deposits_provided",
    "보증금지급": "increasedecrease_in_deposits_provided",
    "기타보증금의지급": "increasedecrease_in_deposits_provided",
    "기타장기보증금의증가": "increasedecrease_in_deposits_provided",
    "임대보증금및예치보증금의증가": "increase_in_deposits_received",
    "종속기업투자주식손상차손환입": "recovery_of_impairment_losses_on_assets",
    "관계기업지분투자손실": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계기업투자비용": "increase_in_investments_in_associatesequity_method_securities",
    "관계회사등투자손익": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계회사주식처분": "decrease_in_investments_in_associatesequity_method_securities",
    "관기업주식처분이익(손실)": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속,관기업처분순현금유입": "decrease_in_investments_in_subsidiaries",
    "종속,관기업투자주식의처분": "decrease_in_investments_in_subsidiaries",
    "종속ㆍ관계기업투자주식관련비용": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업에대한투자자산의추가취득": "increase_in_investments_in_subsidiaries",
    "종속기업유상증자": "paid_in_capital_increase",
    "종속기업의자기주식증가": "increase_in_investments_in_subsidiaries",
    "종속기업주식매수선택권행사": "stock_options",
    "종속기업주식처분이익(손실)": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업지분법자본변동": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업지분법평가": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업지분볍평가": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업투자이익": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업투자주식의추가취득": "increase_in_investments_in_subsidiaries",
    "종속기업투자처분(보유현금성자산차감후)": "decrease_in_investments_in_subsidiaries",
    "종속기업투자현금흐름": "decrease_in_investments_in_subsidiaries",
    "종속기업합병으로인한자본변동": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업합병으로인한현금흐름": "cash_inflows_from_other_investing_activities",
    "종속기업흡수합병으로인한현금유출": "cash_outflows_from_other_investing_activities",
    "종속회사배당": "dividends_paid",
    "종속회사설립": "increase_in_investments_in_subsidiaries",
    "종속회사의소수주주에대한배당": "dividends_paid",
    "종속회사출자": "increase_in_investments_in_subsidiaries",
    "지분법소급적용": "gainslosses_in_equity_method",
    "지분법순이익(손실)": "gainslosses_in_equity_method",
    "지분법이익잉여금조정": "gainslosses_in_equity_method",
    "지분법자본변동-토지재평가": "gainslosses_in_equity_method",
    "지분법적용대상관계기업의기타포괄손익에대한지분": "gainslosses_in_equity_method",
    "지분법적용투자주식처분이익(손실)": "gainslosses_in_equity_method",
    "지분법투자주식처분": "decrease_in_investments_in_associatesequity_method_securities",
    "주식기준보상소멸이익": "stock_options",
    "주식매선택권": "stock_options",
    "주식매수선택권이연법인세효과": "stock_options",
    "주식매수선택원의부여": "stock_options",
    "주식매수선택행사": "stock_options",
    "주식매주선택권의부여": "stock_options",
    "주식발행초과금의자본전입": "paid_in_capital_increase",
    "주식선택권행사비용": "stock_options",
    "주식할인발행차금처분": "paid_in_capital_increase",
    "미행사주식선택권": "stock_options",
    "신주발행(주식선택권)": "stock_options",
    "유상증자(신주발행비)": "paid_in_capital_increase",
    "설립증자": "paid_in_capital_increase",
    "자기주식의처분이익": "gains_on_disposition_of_treasury_stock",
    "자기주식처분손실법인세효과": "losses_on_disposition_of_treasury_stock",
    "사채상환할증금의지급": "decrease_of_longtermbonds",
    "사차의발행": "issuance_of_bonds",
    "전환권대가자본변경": "convertible_bonds",
    "전환권재분류": "convertible_bonds",
    "전환권조정의감소": "convertible_bonds",
    "전환사채재측정요소": "convertible_bonds",
    "전환사채주식발행비용": "convertible_bonds",
    "전환사채청구권행사": "convertible_bonds",
    "전환상환우선주및전환사채의전환": "convertible_bonds",
    "전환상환우선주부채상환할증금": "longterm_preferred_stock_of_redemption",
    "전환상환우선주부채의배당": "longterm_preferred_stock_of_redemption",
    "신종자본증권발행등": "issuance_of_bonds",
    "신주인수권대가등의변동": "stock_options",
    "해외사업장환산차": "reserve_of_exchange_differences_on_translation",
    "해외사업환산손익(비지배지분)": "reserve_of_exchange_differences_on_translation",
    "해외사업환산외환차익": "reserve_of_exchange_differences_on_translation",
    "해외사업환신이익": "reserve_of_exchange_differences_on_translation",
    "해외환산손익(비지배지분)": "reserve_of_exchange_differences_on_translation",
    "외화환산외환차이의세후기타포괄손익": "reserve_of_exchange_differences_on_translation",
    "유형자산재평가잉여금의대체": "revaluation_surplus",
    "유형자산위취득": "acquisition_of_tangible_assets",
    "유형자산취득관련이자지급": "acquisition_of_tangible_assets",
    "재평가손익의변동": "revaluation_surplus",
    "재평가유형자산의매각예정분류": "revaluation_surplus",
    "재평가자산의매각예정분류": "revaluation_surplus",
    "부동산처분재평가잉여금대체": "revaluation_surplus",
    "토지재평가잉여금법인세효과": "revaluation_surplus",
    "토지매각": "disposition_of_tangible_assets",
    "실용신안권": "other_industrial_property_rights",
    "영업권이외의무형자산[개요]": "intangible_assets",
    "무형자산의취득을위한선급": "acquisition_of_intangible_assets",
    "상품의감소(증가)": "decreaseincrease_in_inventories",
    "4.재고자산": "inventories",
    "반환재고회수권": "inventories",
    "영업활동으로인한자산,부채변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "대출채권관련손실": "impairment_losses_on_financial_assets",
    "대출채권관련이익": "recovery_of_impairment_losses_on_financial_assets",
    "금융보증비용(환입）": "other_financial_expenses",
    "금융보증비용의지급": "other_financial_expenses",
    "금융상품대손상각비(대손충당금환입)": "bad_debt_expenses",
    "금융수수료": "other_financial_expenses",
    "금융수수료조정": "other_financial_expenses",
    "금융수익의조정": "financial_income",
    "금융업자산의감소": "decreaseincrease_in_other_financial_institutions_assets",
    "금융업자산의증가": "decreaseincrease_in_other_financial_institutions_assets",
    "기타금융수익(비용)": "other_financial_income",
    "이자수익-유효이자율법에따른이자수익": "interest_income",
    "이자율스왑": "longterm_derivative_assets",
    "이자율스왑평가손실": "losses_on_valuations_of_derivatives",
    "파생상품(전환권)": "longterm_derivative_liabilities",
    "파생상품(전환사채)자본재분류": "longterm_derivative_liabilities",
    "파생상품부채감소": "increasedecrease_in_derivative_liabilities",
    "파생상품부채의취득": "increasedecrease_in_derivative_liabilities",
    "파생상품부채자본변경": "longterm_derivative_liabilities",
    "파생상픔부채의감소": "increasedecrease_in_derivative_liabilities",
    "통화선도거래정산의감소": "longterm_derivative_assets",
    "통화선도거래정산의증가": "longterm_derivative_assets",
    "통화선도자산의정산": "longterm_derivative_assets",
    "통화선도평가손익": "gains_on_valuations_of_derivatives",
    "대행미수금": "other_receivables",
    "대손준비금전입(환입)필요액": "bad_debt_reserve",
    "대손충당금환입(매출채권)": "bad_debt_expenses",
    "매출채권및기타채권손상환입": "bad_debt_expenses",
    "매출부가가치세증가(감소)": "other_current_liabilities",
    "미수금및수취채권(장기)": "trade_and_other_noncurrent_receivables",
    "미수이자수익": "interest_income",
    "(기초)재작성금액": "retained_earnings",
    "(기초자본[수정후])": "equity",
    "기초(재작성후금액)": "retained_earnings",
    "기타(토지취득금액조정)": "acquisition_of_tangible_assets",
    "소모공구비": "other_cost_of_sales",
    "소모품비조정": "other_selling_and_administrative_expenses",
    "기술료수입": "other_operating_income",
    "기타수수료": "other_financial_expenses",
    "기타자본금": "capital_stock",
    "기타불입자본의이입": "other_paid_in_capital",
    "기타불입자본이입액": "other_paid_in_capital",
    "제품수출": "revenue",
    "차량임차료": "other_selling_and_administrative_expenses",
    "클레임비용": "other_cost_of_sales",
    "경상연구개발비조정": "research_and_development_expenses",
    "복리후생비의조정": "employee_benefits",
    "비과세소득으로인한효과": "income_taxes_effects",
    "상각후원가측정자산의감소": "securities_at_amortised_cost",
    "상각후원가측정자산의증가": "securities_at_amortised_cost",
    "사용권자산상각비": "depreciation",
    "기타변동에따른증가(감소),사용권자산": "right_of_use_assets",
    "확정급여제도의측정요소": "remeasurement_elements_of_defined_benefit_plans",
    "(세후)순확정급여부채의재측정요소": "remeasurement_elements_of_defined_benefit_plans",
    "보험의수리적손익": "remeasurement_elements_of_defined_benefit_plans",
    "손확정급여부채": "net_defined_benefit_liabilities",
    "순확접급여부채의재측정요소": "remeasurement_elements_of_defined_benefit_plans",
    "이익준비금의전입": "retained_earnings",
    "자본금입금": "capital_stock",
    "자본에직접인식된거래합계": "equity",
    "자본준비금감액및이익잉여금전입": "retained_earnings",
    "소요주와의거래총액": "equity",
    "우리사주": "treasury_stock",
    "국고보조금상환채무의증가": "government_grants",
    "국고보조금자산의증가": "government_grants",
    "정부보조금(무형자산)의수령": "government_grants",
    "정부보조금(유형자산)의수령": "government_grants",
    "정부보조금의지급": "government_grants",
    "정부보증금의감소": "government_grants",
    "배출자산": "other_noncurrent_assets",
    "비금융기타채무": "other_current_liabilities",
    "비유동파생금융부채": "longterm_derivative_liabilities",
    "공모사채분담금환입": "other_nonoperating_income",
    "상장합병비용": "other_nonoperating_expenses",
    "합병신주발행비용": "paid_in_capital_increase",
    "합병으로인한자금유출": "cash_outflows_from_other_investing_activities",
    "합병으로인한취득": "cash_inflows_from_other_investing_activities",
    "흡수합병으로인한변동": "equity",
    "사업결합으로인한순현금의감소": "cash_outflows_from_other_investing_activities",
    "사업결합으로인한현금흐름의유입": "cash_inflows_from_other_investing_activities",
    "SPAC과합병으로인한현금유입액": "cash_inflows_from_other_investing_activities",
    "투자부동산취득세환급": "cash_inflows_from_other_investing_activities",
    "투자유가증권(매도가능증권)의취득(감소)": "decrease_in_investments_in_associatesequity_method_securities",
    "투자유가증권평가손익": "gains_on_valuation_of_availableforsale_financial_assets",
    "무상증자관련비용": "capital_increase_decrease_without_consideration",
    "선수금-고정자산의증가": "increasedecrease_in_advance_from_customers",
    "건설증자산의취득": "acquisition_of_tangible_assets",
    "IFRS1115호효과": "retained_earnings",
    "손상손실": "impairment_losses_on_assets",
    "비지배지분부채평가손실": "noncontrolling_interests_equity",
    "비지배지분부채평가이익": "noncontrolling_interests_equity",
    "반기순이익(손실)의귀속": "net_income",
    "당기계속사업총포괄손익": "total_comprehensive_income",
    "당기중단사업총포괄손익": "total_comprehensive_income",
    "지배기업의소유주계속영업이익(손실)": "owners_of_parent_equitynet_income",
    "보통주기본,희석주당이익(손실)": "earnings_per_share",
    "우선주기본,희석주당이익(손실)": "earnings_per_share",
    "기타비유동금융부채의순증가(감소)": "increasedecrease_in_other_financial_liabilities",
    "기타비유동부채금융부채의증가": "increase_in_other_financial_liabilities",
    "기타비유동부채의상환": "decrease_in_noncurrent_liabilities",
    "단가차입금의순증감": "increasedecrease_in_shortterm_borrowings",
    "단기여금의증가": "increase_in_shortterm_loans",
    "유동성장기임대보증금": "current_portion_of_longterm_debt",
    "유동성장기임대보증금의증가": "current_portion_of_longterm_debt",
    "유동성장기차입": "current_portion_of_longterm_debt",
    "유동성장기차입급의상환": "decrease_in_current_portion_of_longterm_assetbacked_debts",
    "유동성장기치압금의상환": "decrease_in_current_portion_of_longterm_assetbacked_debts",
    "유동성회생담보채무의상환": "decrease_in_current_portion_of_longterm_assetbacked_debts",
    "상환부채의증가": "increase_in_longtermborrowings",
    "장기기타비유동채권의감소": "trade_and_other_noncurrent_receivables",
    "장기기타수취채권의증감": "decreaseincrease_in_loans_and_receivables",
    "장기기타수취채권이감소": "decreaseincrease_in_loans_and_receivables",
    "장기차입금의감소(조기상환)": "decrease_in_longtermborrowings",
    "입회금의감소": "increasedecrease_in_deposits_provided",
    "입회금의증가": "increasedecrease_in_deposits_provided",
    "시설물이용권의처분": "disposition_of_intangible_assets",
    "처분집단의현금및현금성자산": "cash_and_cash_equivalents",
    "업무추진비,판관비": "other_selling_and_administrative_expenses",
    "판매촉진비,판관비": "other_selling_and_administrative_expenses",
    "지급보증부채의지급": "other_financial_expenses",
    "연차수당충당급전입액": "provisions_for_employee_benefits",
    "제3자배정콜옵션관련기초조정": "stock_options",
    "연결범위변동으로인한순감소": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "연결범위변동으로인한증가액": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "연결변동으로인한현금유입": "cash_inflows_from_other_investing_activities",
    "연결실체변동으로인한증가": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "연결실체의변동": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "열결범위의변동": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "연결대상범위의변동,재무활동": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "회생채권의회수": "cash_inflows_from_other_investing_activities",
    "자기주식소각,재무활동": "treasury_stock",
    "단기투자자산의증가": "increase_in_shortterm_financial_instruments",
    "기타손익(손실)": "other_nonoperating_gainslosses",
    "무형자산의환급": "disposition_of_intangible_assets",
    "사후처리,복구,정화비용을위한충당부채[개요]": "provisions_for_restoration_costs",
    "유동당기손익인식금융자산[개요]": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "기타포괄손익-공정가치측정금융자산[개요]": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "만기보유금융자산-비유동": "held_to_maturity_financial_assets",
    "매도가능금융자산-비유동": "longterm_availableforsale_financial_assets",
    "만기보유금융자산-유동": "held_to_maturity_financial_assets",
    "유동성장차입금의감소": "decrease_in_current_portion_of_longterm_assetbacked_debts",
    "당기환급금자산": "other_current_assets",
    "매각예정분류기타자본구성요소": "other_paid_in_capital",
    "종속기업투자주식의추가취득": "increase_in_investments_in_subsidiaries",
    "전환우선주부채의평가손익": "longterm_preferred_stock_of_redemption",
    "당기손익-공정가치지정금융부채전환": "longterm_financial_liabilities",
    "미지급배당금의증감": "dividends_paid",
}

# Verify
missing_ids = set()
valid_mapping = {}
for name, sid in mapping.items():
    if sid in allSnakeIds:
        valid_mapping[name] = sid
    else:
        missing_ids.add(sid)
        print(f"  SKIP (missing snakeId): {name} -> {sid}")

print(f"\nTotal mapping: {len(mapping)}")
print(f"Valid: {len(valid_mapping)}")
print(f"Skipped: {len(mapping) - len(valid_mapping)}")

if valid_mapping:
    result = learner.learnBatch(valid_mapping)
    print(f"\nlearnBatch: {result}/{len(valid_mapping)} success")
    print(f"Total synonyms: {len(learner._synonyms)}")
