"""25차 대량 학습: 3-unmapped 119개 종목 대상 357개 계정 매핑"""

import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[5]))

from core.dart.searchDart.finance.v7.synonymLearner import SynonymLearner

sl = SynonymLearner()
print(f"학습 전 동의어: {sl.synonymCount}")

mapping = {
    # === 차입금 관련 (4개) ===
    "단기차입금외화환산손실": "foreign_exchange_losses",
    "사채및차입금": "borrowings",
    "외화단기차입금의차입": "shortterm_borrowings",
    "외화장기차입금의차입": "longterm_borrowings",
    # === 파생 관련 (6개) ===
    "내재파생상품자산": "shortterm_derivative_assets",
    "파생금융상품의증감": "shortterm_derivative_assets",
    "파생금융상품자산(비유동)": "longterm_derivative_assets",
    "파생상품자산증가": "shortterm_derivative_assets",
    "파생상품자산취득": "shortterm_derivative_assets",
    "현금흐름위험회피파생상품손익": "gains_on_valuations_of_derivatives",
    # === 공정가치 관련 (19개) ===
    "(3)기타포괄-공정가치측정금융자산평가이익": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "공정가치-기타포괄손익금융자산": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손손익-공정가치측정금융자산처분손실": "losses_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익-공정가치측정금융자산의증가(감소)": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익_공정가치측정금융자산": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익_공정가치측정자산": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익－공정가치금융자산처분손익": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익－공정가치로측정하는지분상품의공정가치변동": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포손익-공정가치금융자산": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "당기손익-공정가치금융부채의처분": "losses_on_disposal_of_financial_liabilities_measured_at_fair_value_through_profit_or_loss",
    "당기손익-공정가치측정금융부채처분손익": "gains_on_disposal_of_financial_liabilities_measured_at_fair_value_through_profit_or_loss",
    "당기손익-공정가치측정금융자산관련이익": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익-공정가치측정금융자산관련손실": "losses_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익-공정가치측정금융자산의증가": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익-공정가치측정금융자산처분이익(손실)": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익공정가치금융자산관련이익": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익공정가치금융자산관련이익(손실)": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익공정가치측정금융자산의처분": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익인식공정가치측정유가증권의처분": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    # === 종속/관계기업 관련 (26개) ===
    "관계기업및종속기업기타포괄손익에대한지분": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "비연결종속기업의처분": "gains_on_disposition_of_subsidiaries",
    "비연결종속기업의회수": "gains_on_disposition_of_subsidiaries",
    "종속기업,관계기업투자손실": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업,관계기업투자이익": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업및관계기업지분법손실": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속기업및관계기업투자주식처분": "gains_on_disposition_of_subsidiaries",
    "종속기업비지배주주지분": "noncontrolling_interests_equity",
    "종속기업순손익에대한지분": "gainslosses_in_subsidiaries",
    "종속기업의현금의증감": "gainslosses_in_subsidiaries",
    "종속기업지분변동": "gainslosses_in_subsidiaries",
    "종속기업투자기업의처분": "gains_on_disposition_of_subsidiaries",
    "종속기업투자손실(이익)": "gainslosses_in_subsidiaries",
    "종속기업투자주식감소": "gains_on_disposition_of_subsidiaries",
    "종속기업투자주식의취득": "investments_in_subsidiaries",
    "종속및공동기업포괄손익지분": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속지업투자주식취득": "investments_in_subsidiaries",
    "종속회사/관계기업기타포괄손익": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계기업기타포괄순손익에대한지분": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계기업대한지분": "investments_in_associates",
    "관계기업순손익지분": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계기업의해외사업장외화환산차이(기타포괄손익)": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계기업투자주식출자금반환": "investments_in_associates",
    "관계기업투자주식취득관련장기선급금의증가": "investments_in_associates",
    "관계기업투자처분": "gains_on_disposition_of_investments_in_associates",
    "장기선급금(관계기업투자)의증가": "investments_in_associates",
    # === 리스/사용권 관련 (12개) ===
    "금율리스부채의상환": "repayment_of_lease_liabilities",
    "단기리스채권의증가": "leasedrightofuse_assets",
    "리스변경차익": "gains_on_disposition_of_leasedrightofuse_assets",
    "리스부채(비유동)의감소(증가)": "repayment_of_lease_liabilities",
    "리스부채감소에따른현금유출": "repayment_of_lease_liabilities",
    "리스자산부채의상환": "repayment_of_lease_liabilities",
    "선급리스자산평가손실": "impairment_losses_on_leasedrightofuse_assets",
    "운용리스부채": "lease_liabilities",
    "유동성리스금융부채": "lease_liabilities",
    "장기리스채권의감소": "leasedrightofuse_assets",
    "장기리스채권의증가": "leasedrightofuse_assets",
    "장기리스채권증가": "leasedrightofuse_assets",
    # === 충당부채 관련 (4개) ===
    "금융보증충당부채전입액(환입액)": "longterm_provisions",
    "보증충당부채전입액": "longterm_provisions",
    "소송충당금전입": "longterm_provisions",
    "품질보증충당부채": "longterm_provisions",
    # === 보증금 관련 (9개) ===
    "기타보증금(부채)의감소": "decrease_in_deposits_provided",
    "기타보증금취득": "longterm_gurarantee",
    "보증금현재가치할인차금": "longterm_gurarantee",
    "예수보증금이증가": "increase_in_deposits_received",
    "임대보증금(유동)감소": "decrease_in_leasehold_deposits_received",
    "임대보증금의중가": "increase_in_leasehold_deposits_received",
    "장기보증금및선급비용의증가": "longterm_gurarantee",
    "장기예수보증금의감소(증가)": "decrease_in_deposits_received",
    "장기예수보증금증가(감소)": "increase_in_deposits_received",
    # === 합병 관련 (3개) ===
    "Ⅳ.합병으로인한현금흐름": "cash_inflows_from_merger_and_acquisition",
    "합병법인세납부": "income_tax_paid",
    "합병상장비용": "other_nonoperating_expenses",
    # === 포괄손익 관련 (9개) ===
    "기타포괄손익-고엉가치측정금융자산처분손익": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익:후속적으로당기손익으로재분류되는항목-해외사업환산손익": "reserve_of_exchange_differences_on_translation",
    "기타포괄손익공정가지금융자산의취득": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "기타포괄손익인식금융자산평가이익": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "매도가능금융자산평가손익(기타포괄손익-지분상품)": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "연결반기기타포괄손익": "other_comprehensive_income",
    "연결분기기타포괄손익": "other_comprehensive_income",
    "포괄손익[개요]": "other_comprehensive_income",
    "포괄손익인식금융자산평가손익": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    # === 자본 관련 (8개) ===
    "II.자본에직접인식된주주와의거래": "total_stockholders_equity",
    "법인세비용(자본에직접가감)": "income_tax_expense",
    "연결기타자본잉여금": "other_capital_surplus",
    "영업양수관련자본잉여금": "other_capital_surplus",
    "운전자본의증가": "net_income",
    "자본조정의이익잉여금대체": "retained_earnings",
    "자본준비금이익잉여금대체": "retained_earnings",
    "지분법자본변동누계액": "gainslosses_in_subsidiaries_joint_ventures_associates",
    # === 법인세 관련 (3개) ===
    "(12)미지급법인세": "income_tax_payable",
    "관련법인세": "income_tax_expense",
    "법인세효": "income_tax_expense",
    # === 감가상각 관련 (3개) ===
    "감가상각비및무형자산상각비": "depreciation_and_amortization",
    "임대자산감가상각비": "depreciation_of_investment_properties",
    "투자부동산감가상각비,판관비": "depreciation_of_investment_properties",
    # === 손상 관련 (4개) ===
    "기타의대손상각비의증가": "expenses_of_allowance_for_doubtful_accounts",
    "매도가능금융자산의처분/손상으로인한재분류": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "매도가능금융자산처분/손상으로인한재분류": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "지분법적용투자손상차손": "impairment_losses_on_investments_in_associates",
    # === 처분 관련 (9개) ===
    "매각예정비유동자산처분계약금": "gains_on_disposition_of_property_and_equipment",
    "매각예정처분부채의지급": "other_nonoperating_expenses",
    "매강예정처분부채의지급": "other_nonoperating_expenses",
    "매도가능금융자산(지분상품)의처분": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "매도가능금융자산처분으로인한평가이익감소": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "유형자산처분미수금의감소": "gains_on_disposition_of_property_and_equipment",
    "장기금융삼품의처분": "longterm_financial_instruments",
    "투자부동산처분계약금": "gains_on_disposition_of_investment_properties",
    "현금창출단위(CGU)처분으로인한순현금흐름": "gains_on_disposition_of_property_and_equipment",
    # === 환율 관련 (7개) ===
    "Ⅵ.현금성자산의환율변동효과": "difference_by_changes_in_foreign_exchange_rates",
    "외화표시현금및현금설자산의환율변동효과": "difference_by_changes_in_foreign_exchange_rates",
    "외화표시환율변동의효과": "difference_by_changes_in_foreign_exchange_rates",
    "외화현금에대한환율변동효과": "difference_by_changes_in_foreign_exchange_rates",
    "해외사업환산으로인한환율차이": "reserve_of_exchange_differences_on_translation",
    "현금및현금성자산에대한환율변동효과_": "difference_by_changes_in_foreign_exchange_rates",
    "환율변동효과로인한변동액": "difference_by_changes_in_foreign_exchange_rates",
    # === 연결 관련 (6개) ===
    "연결대상범위(지배력의취득)": "gainslosses_in_subsidiaries",
    "연결대상범위변동": "gainslosses_in_subsidiaries",
    "연결범위포함으로인한현금의감소": "gainslosses_in_subsidiaries",
    "연결실체변동으로인한현금증가": "gainslosses_in_subsidiaries",
    "연결실체변동효과": "gainslosses_in_subsidiaries",
    "연결실체의변동으로인한증가": "gainslosses_in_subsidiaries",
    # === 중단 관련 (6개) ===
    "중단산업손익": "discontinued_operating_incomeloss",
    "중단영업의재무활동으로인한현금유입(유출)": "cash_flows_from_discontinued_operating",
    "중단영업현금의순증감": "cash_flows_from_discontinued_operating",
    "중단영업활동현금흐름": "cash_flows_from_discontinued_operating",
    "중단재무활동현금흐름": "cash_flows_from_discontinued_operating",
    "중단투자활동현금흐름": "cash_flows_from_discontinued_operating",
    # === 재측정 관련 (5개) ===
    "곽계기업의재측정요소": "remeasurement_elements_of_defined_benefit_plans",
    "순확정급여부채에대재측정요소": "remeasurement_elements_of_defined_benefit_plans",
    "순확정급여부채에대한재측정요": "remeasurement_elements_of_defined_benefit_plans",
    "순확정급여의재측정요소(보험수리적손익)": "remeasurement_elements_of_defined_benefit_plans",
    "확정급여부채의재측정요": "remeasurement_elements_of_defined_benefit_plans",
    # === 기타 (214개 중 주요 계정) ===
    "(10)기타유동부채": "other_current_liabilities",
    "(2)재평가잉여금": "revaluation_surplus",
    "2.재평가잉여금": "revaluation_surplus",
    "거래가격차이이연자산": "other_noncurrent_assets",
    "거래일평가손실": "other_nonoperating_expenses",
    "건설중인자산감소": "tangible_assets",
    "경상개발비지출": "research_and_development_costs",
    "경상연구개발비(감가상가비)": "research_and_development_costs",
    "계속영업현금의순증감": "net_income",
    "공급자금융약정으로인한감소": "other_current_liabilities",
    "국외사업장관련이익잉여금변동": "retained_earnings",
    "금융리스채무의원금상환": "repayment_of_lease_liabilities",
    "기말의매각예정자산에포함된현금및현금성자산": "cash_and_cash_equivalents",
    "기말의현금및현금등가물": "cash_and_cash_equivalents",
    "기초의현금및현금등가물": "cash_and_cash_equivalents",
    "기타단기금융자산(부채)": "other_current_financial_assets",
    "기타단기비금융부채의증가": "other_current_liabilities",
    "기타대금의증가": "other_current_assets",
    "기타매출(매입)채무의증가": "other_current_liabilities",
    "기타비유동금융부채의차입": "other_longterm_financial_liabilities",
    "기타비유동부채의증감": "other_noncurrent_liabilities",
    "기타비유동자산,부채의증감": "other_noncurrent_assets",
    "기타비유동충당부채전입": "longterm_provisions",
    "기타사업비": "sga",
    "기타영업활동으로인한자산및부채의감소": "other_current_assets",
    "기타유동금융자산(부채)": "other_current_financial_assets",
    "기타유동부채의증가": "other_current_liabilities",
    "기타유동자산,부채의증감": "other_current_assets",
    "기타이익잉여금의증가": "retained_earnings",
    "기타장기금융자산(부채)": "other_longterm_financial_assets",
    "기타잡이익(손실)": "other_nonoperating_income",
    "기타조정사항": "net_income",
    "단기금융자산(부채)의순증감": "shortterm_financial_instruments",
    "단기금융자산의증감": "shortterm_financial_instruments",
    "단기대여금의감소(증가)": "decrease_in_shortterm_loans",
    "단기매매금융부채관련손실": "losses_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "단기매매금융자산관련이익": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기비용인식한리스부채상환액": "repayment_of_lease_liabilities",
    "당기손익-공정가치지정금융부채처분손익": "gains_on_disposal_of_financial_liabilities_measured_at_fair_value_through_profit_or_loss",
    "당기손익측정금융자산의증가": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "대출채권평가": "financial_assets_at_amortised_cost",
    "대여금및예치금의증감": "decrease_in_shortterm_loans",
    "매각예정자산관련기말의현금및현금성자산": "cash_and_cash_equivalents",
    "매각예정비유동자산분류조정": "other_noncurrent_assets",
    "매도가능자산의취득": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "매입채무및기타유동금융부채의증감": "increasedecrease_in_trade_and_other_payables",
    "무형자산손상차손(상각비)": "impairment_losses_on_intangible_assets",
    "무형자산취특": "intangible_assets",
    "미수금감소(증가)": "decreaseincrease_in_other_receivables",
    "미인식과거근무원가": "sga",
    "미지급법인세의증가(감소)": "income_tax_payable",
    "배당금의배분": "dividends",
    "배당금지급(수입)": "dividends",
    "별도배당금수령": "dividends",
    "보통주기타자본": "other_reserves",
    "보통주발행주식총수": "issued_common_stocks",
    "불법행위미수금": "other_current_assets",
    "비유동금융부채의차입/상환": "longterm_borrowings",
    "비유동금융자산의감소(증가)": "other_longterm_financial_assets",
    "비유동매도가능금융자산": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "비유동차입금및사채의감소": "repayment_of_longterm_borrowings",
    "비지배지분당기순이익": "noncontrolling_interests_equity",
    "비지배지분당기총포괄이익": "noncontrolling_interests_equity",
    "비지배지분의변동(순액)": "noncontrolling_interests_equity",
    "사업양수관련자금유입": "cash_inflows_from_merger_and_acquisition",
    "사용권자산상각": "depreciation_of_leasedrightofuse_assets",
    "사채및유동성차입금의상환": "repayment_of_longterm_borrowings",
    "상각후원가측정금융자산(비유동자산)": "financial_assets_at_amortised_cost",
    "상각후원가측정유가증권의증감": "financial_assets_at_amortised_cost",
    "상각후원가츨정유가증권의감소": "financial_assets_at_amortised_cost",
    "선급금공사비의증가": "advance_paymentsconstruction_outside_processing_expenses",
    "선급금외": "advance_payments",
    "선수금환불/지급": "advances_received",
    "소송으로인한예수금의감소": "other_current_liabilities",
    "소송으로인한예수금의반환": "other_current_liabilities",
    "수입보증금및전수금의증가(감소)": "increase_in_deposits_received",
    "신규리스부채인식": "lease_liabilities",
    "신주인수권대가조정": "other_capital_surplus",
    "신주인수권부사채행사": "paid_in_capital_increase",
    "우량주식및채권의취득": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "우선주기타자본": "other_reserves",
    "원가로평가하는비유동지분상품": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "유동금융부채상환(차입)": "repayment_of_shortterm_borrowings",
    "유동비금융부채의증가": "other_current_liabilities",
    "유동성대환": "current_portion_of_longterm_borrowings",
    "유동성상각후원가측정유가증권의감소": "financial_assets_at_amortised_cost",
    "유동성상각후원가츨정유가증권의감소": "financial_assets_at_amortised_cost",
    "유무형자산취득관련미지급비용의지급": "tangible_assets",
    "유형자산감소(폐기등)": "disposal_of_tangible_assets",
    "유형자산비용감가상각비": "depreciation_of_tangible_assets",
    "이익잉여금의적립": "retained_earnings",
    "이익잉여금의처분": "retained_earnings",
    "인수시현금": "cash_and_cash_equivalents",
    "임대보증금등의증가": "increase_in_leasehold_deposits_received",
    "임대차보증금등의감소": "decrease_in_leasehold_deposits_received",
    "임차보증금및기타자산": "longterm_gurarantee",
    "자기신주인수권소멸": "other_reserves",
    "자산평가조정(투자주식)": "investments_in_associates",
    "자산항목의감소(영업)": "other_current_assets",
    "장기금융자산의증가(순)": "other_longterm_financial_assets",
    "장기대여금감소": "decrease_in_longterm_loans",
    "장기매도가능금융자산": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "장기성상각후원가측정유가증권의증가": "financial_assets_at_amortised_cost",
    "장기전환권부사채의감소": "repayment_of_longterm_borrowings",
    "재고자산매출원가환원": "cost_of_goods_sold",
    "재고자산의감소(가격변동)": "inventories",
    "전기오류수정이익": "retained_earnings",
    "전기오류수정이익(손실)": "retained_earnings",
    "전기오류수정효과": "retained_earnings",
    "전환권(조기상환권)조정": "longterm_borrowings",
    "전환사채재매입": "repayment_of_longterm_borrowings",
    "전환상환우선주부채할인발행차금": "longterm_borrowings",
    "정부보조금(부채)의증감": "government_grants_deferred_income",
    "정부보조금차감후기말현금및현금성자산": "cash_and_cash_equivalents",
    "주식매수선태권소멸": "stock_option",
    "주식배당금(현물배당금)지급": "dividends",
    "주식보상보상비용": "stock_option",
    "지급임차료환원(운용리스)": "sga",
    "지배기업주주귀속총포괄이익": "net_income",
    "지배기업주주지분당기순이익": "net_income",
    "지배기업주주지분당기총포괄이익": "net_income",
    "퇴직급여관련부채의증가": "increasedecrease_in_provisions_for_employee_benefits",
    "퇴직연금의납부": "related_payments_of_retirement_allowance",
    "투자부동산처분미수금": "gains_on_disposition_of_investment_properties",
    "투자활동으로로인한현금유출액": "cash_flows_from_investing_activities",
    "특별이익": "other_nonoperating_income",
    "현금및현금성자산의기초금액": "cash_and_cash_equivalents",
    "현금및현금성자산의기말금액": "cash_and_cash_equivalents",
    "현물출자로인한현금유출액": "investments_in_subsidiaries",
    "현물출자로인한현금유출(입)액": "investments_in_subsidiaries",
    "회원권의취득": "other_noncurrent_assets",
    "회원권의처분": "other_noncurrent_assets",
    "후순위채권의처분": "financial_assets_at_amortised_cost",
    "후순위차입금의차입": "longterm_borrowings",
    "해외사업장관련이익잉여금변동": "retained_earnings",
    "복리후생비조정": "sga",
    "사채(당기법인세포함)": "bonds",
    "유동금융비용": "interest_expense",
    "토지이용재평가차익": "revaluation_surplus",
    "보험계약(자산)부채": "reinsurance_assets",
    "신종자본증권이자": "hybrid_bond_accrued_interest_payables",
    "전환권조정의상각": "interest_expense",
}

count = sl.learnBatch(mapping)
print(f"학습 완료: {count}개")
print(f"학습 후 동의어: {sl.synonymCount}")
