import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
sys.path.insert(0, ".")
from core.dart.searchDart.finance.v7.synonymLearner import SynonymLearner

sl = SynonymLearner()

directMappings = {
    "집기와비품의처분": "decrease_in_tools_and_office_equipment",
    "기타(중소기업유상감자)": "paid_in_capital_decrease",
    "리스해지손익": "other_nonoperating_gainslosses",
    "유동성예수부채": "current_portion_of_longterm_debt",
    "유동성전환부채": "current_portion_of_longterm_debt",
    "유동성전환금융상품": "current_portion_of_longterm_debt",
    "보상금이익": "other_nonoperating_revenues",
    "기타현금흐름": "other_cash_flows_from_operating_investing_financing_activities",
    "납입액": "paid_in_capital_increase",
    "기타증감액": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타의자산의감소(증가)": "decreaseincrease_in_assets",
    "리스해지이익의조정": "other_nonoperating_gainslosses",
    "자산수증이익조정": "other_nonoperating_revenues",
    "태양광발전설비의증가": "property_plant_and_equipment",
    "도급비": "advance_paymentsconstruction_outside_processing_expenses",
    "계정분류에따른증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "운송비": "transportation_expenses",
    "리스처분손익": "other_nonoperating_gainslosses",
    "VI.조정": "changes_in_assets_and_liabilities_from_operating_activities",
    "리스순투자의회수": "cash_flows_from_investing",
    "기타의비유동자산": "other_noncurrent_financial_assets",
    "유동전대리스순투자의감소": "cash_flows_from_investing",
    "챠량운반구의처분": "decrease_in_motor_vehicles",
    "영업자산·부채의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "유형의자산": "property_plant_and_equipment",
    "자사주상여": "treasury_stock",
    "기타수추채권(비유동)의감소": "decrease_in_other_noncurrent_assets",
    "국·공채의처분": "cash_flows_from_investing",
    "유셩자산폐기손실": "losses_on_disposal_of_assets",
    "부가세대급급의증가(감소)": "changes_in_assets_and_liabilities_from_operating_activities",
    "재고감모와매각손": "inventory",
    "자산.부채의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "(유동성)장기부채의증가": "increase_in_current_portion_of_longterm_debt",
    "기타장기채무의증가(감소)": "other_noncurrent_liabilities",
    "공장이전보상금": "other_nonoperating_revenues",
    "리스중도해지손익": "other_nonoperating_gainslosses",
    "열공급설비": "property_plant_and_equipment",
    "자산·부채변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "파생삼품의결제": "cash_flows_from_investing",
    "자사주처분": "sale_of_treasury_stock",
    "전환의행사": "paid_in_capital_increase",
    "영업자산·부채의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "수입장려금": "other_nonoperating_revenues",
    "리스관련차익": "other_nonoperating_revenues",
    "퇴직/연차": "severance_and_retirement_benefits",
    "전한권의행사": "paid_in_capital_increase",
    "3.자산부채증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "예상공사이익": "other_nonoperating_revenues",
    "인수대가의정산": "cash_flows_from_investing",
    "자기기준보상행사": "cash_flows_from_financing_activities",
    "기타영엽외손익": "other_nonoperating_gainslosses",
    "제품평가손실(환입)": "inventory",
    "지분매각": "disposal_of_tangible_assets",
    "리스해지의손익": "other_nonoperating_gainslosses",
    "렌탈자산및선급렌탈자산의증가": "property_plant_and_equipment",
    "유동성파생부채의감소": "cash_flows_from_financing_activities",
    "채권추심이익": "other_nonoperating_revenues",
    "계속포괄이익(손실)": "total_comprehensive_income",
    "리스유동채권의감소(증가)": "trade_and_other_current_receivables",
    "리스중단이익": "other_nonoperating_revenues",
    "거래일손익조정액상각": "other_nonoperating_gainslosses",
    "자산및부채증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "자본전환": "paid_in_capital_increase",
    "잡손실환입": "other_nonoperating_revenues",
    "기술이전료수입": "other_nonoperating_revenues",
    "기타비유동금융부재의처분": "cash_flows_from_financing_activities",
    "파생생품현금증가(감소)": "cash_flows_from_investing",
    "자본거래에따른지출": "cash_flows_from_financing_activities",
    "기타세율변경효과": "taxes_expenses",
    "지분매도": "disposal_of_tangible_assets",
    "선급주세": "prepaid_expenses",
    "파생부채의감소": "cash_flows_from_financing_activities",
    "파상상품자산": "shortterm_derivative_assets",
    "상여금의지급": "salaries_and_wages",
    "연구용자산의증가": "property_plant_and_equipment",
    "장기채무의감소": "cash_flows_from_financing_activities",
    "전화권의행사": "paid_in_capital_increase",
    "영엽외손익": "other_nonoperating_gainslosses",
    "단기금웅상품의처분": "decrease_in_shortterm_financial_instruments",
    "기타사항": "other_cash_flows_from_operating_investing_financing_activities",
    "기타의유동자산증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타불입자본의증가": "capital_surplus",
    "자기자본": "stockholders_equity",
    "연차수당및장기근속수당": "salaries_and_wages",
    "리스채권의순증감": "trade_and_other_current_receivables",
    "타계정에서대체": "changes_in_assets_and_liabilities_from_operating_activities",
    "매점수입": "other_nonoperating_revenues",
    "운전자분의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "분할": "cash_flows_from_financing_activities",
    "조정과목": "changes_in_assets_and_liabilities_from_operating_activities",
    "유상증가": "paid_in_capital_increase",
    "자사주의매입": "purchase_of_treasury_stock",
    "공기구의증가": "increase_in_tools_and_office_equipment",
    "비유동파생자산": "longterm_derivative_assets",
    "자기주신처분": "sale_of_treasury_stock",
    "보상비조정": "changes_in_assets_and_liabilities_from_operating_activities",
    "(4)운전자본변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타비유동금융채무의감소": "other_noncurrent_liabilities",
    "공사원재료": "raw_materialssubmaterials",
    "기타의비유동자산의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타의투자자산회수": "cash_flows_from_investing",
    "유동화부채의증감": "cash_flows_from_financing_activities",
    "지분거래이익": "other_nonoperating_revenues",
    "조정:": "changes_in_assets_and_liabilities_from_operating_activities",
    "통화선부채의증가": "cash_flows_from_financing_activities",
    "이익조정을위한가감": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타수쉬채권의증가": "trade_and_other_current_receivables",
    "기타종업원자산": "other_current_assets",
    "기타단기유동부채": "other_current_liabilities",
    "기타종업원부채": "other_current_liabilities",
    "기타비유동수취채권의감소(중가)": "decrease_in_other_noncurrent_assets",
    "투자차액": "cash_flows_from_investing",
    "기타의소계": "changes_in_assets_and_liabilities_from_operating_activities",
    "이자의지금": "interest_expenses",
    "포괄이익": "total_comprehensive_income",
    "리스설비": "leased_assets",
    "이자손익": "net_interest_expenses",
    "기타현금의유출": "other_cash_flows_from_operating_investing_financing_activities",
    "기타의투자자산의회수": "cash_flows_from_investing",
    "지분매각으로인한현금의감소": "cash_flows_from_investing",
    "기타합계": "other_cash_flows_from_operating_investing_financing_activities",
    "유동리스": "leased_assets",
    "기타투자자신의감소": "cash_flows_from_investing",
    "기타의현금증가": "other_cash_flows_from_operating_investing_financing_activities",
    "영업관련자산.부채의조정": "changes_in_assets_and_liabilities_from_operating_activities",
    "유동성파생자산/부채의처분": "cash_flows_from_investing",
    "기타비유동채": "other_noncurrent_liabilities",
    "관리운용순익": "other_nonoperating_revenues",
    "유상감자로인한증가": "paid_in_capital_decrease",
    "기타투주자산의감소": "cash_flows_from_investing",
    "장기미급금의증가": "other_noncurrent_liabilities",
    "전대리스이익": "other_nonoperating_revenues",
    "통화옵션부채": "shortterm_derivative_liabilities",
    "유동리스채권감소": "trade_and_other_current_receivables",
    "용지의감소(증가)": "property_plant_and_equipment",
    "기타지분변동": "cash_flows_from_financing_activities",
    "유동성전대리스순투자의감소": "cash_flows_from_investing",
    "자기자슥의처분": "sale_of_treasury_stock",
    "세전이익(손실)": "pretax_profit_from_continuing_operations",
    "기타자산(비유동)의처분": "decrease_in_other_noncurrent_assets",
    "리스채권손실": "other_nonoperating_expenses",
    "공동기업의순손익에대한지분증감": "losses_on_valuation_of_equity_method_securities",
    "대체와기타변동에따른증가(감소)": "changes_in_assets_and_liabilities_from_operating_activities",
    "운전항목의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "유성성장기부채의증가": "increase_in_current_portion_of_longterm_debt",
    "영업할동으로인한자산과부채의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "상품폐기손실": "other_nonoperating_expenses",
    "기타자산처분": "cash_flows_from_investing",
    "순운전자본의변동(주석28)": "changes_in_assets_and_liabilities_from_operating_activities",
    "(2)조정:": "changes_in_assets_and_liabilities_from_operating_activities",
    "유현자산폐기손실": "losses_on_disposal_of_assets",
    "임직원포상": "salaries_and_wages",
    "기타투자자자산의증가": "cash_flows_from_investing",
    "총포손익소계": "total_comprehensive_income",
    "유동성전환상채": "current_portion_of_longterm_debt",
    "선납지방소득세": "prepaid_expenses",
    "기타의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타충당채무": "longterm_provisions",
    "유동장기채무의감소": "current_portion_of_longterm_debt",
    "기타순손실": "other_nonoperating_expenses",
    "공기구비품의증가": "increase_in_tools_and_office_equipment",
    "기타의증가(감소)": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타유동부체": "other_current_liabilities",
    "비유동부채의증가(감소)": "other_noncurrent_liabilities",
    "유동예수부채": "current_portion_of_longterm_debt",
    "전환청구": "paid_in_capital_increase",
    "기타투자사산의감소": "cash_flows_from_investing",
    "금융이익-기타": "gains_on_disposition_of_other_financial_assets",
    "유동파생금유부채": "shortterm_derivative_liabilities",
    "유동성주임종단기채권의감소": "cash_flows_from_investing",
    "금형의증가": "property_plant_and_equipment",
    "기타단기금융상품감소(증가)": "decrease_in_shortterm_financial_instruments",
    "기타증가(감소)": "changes_in_assets_and_liabilities_from_operating_activities",
    "파생자산상품의매각": "cash_flows_from_investing",
    "지배지분총포괄익": "total_comprehensive_incomeowners_of_parent_equity",
    "자본의증가(감소)": "stockholders_equity",
    "기타전입액": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타(주식발행비)": "capital_surplus",
    "지붑법손실": "losses_on_valuation_of_equity_method_securities",
    "기타비유동금웅자산": "other_noncurrent_financial_assets",
    "기타조정등": "changes_in_assets_and_liabilities_from_operating_activities",
    "지속적관여의감소": "cash_flows_from_investing",
    "인테리어": "leasehold_improvements",
    "보증손실환입": "other_nonoperating_revenues",
    "복구공사이익": "other_nonoperating_revenues",
    "미수법인환급세": "prepaid_expenses",
    "채무면제이익대체": "other_nonoperating_revenues",
    "기타항목손익": "other_nonoperating_gainslosses",
    "조정.": "changes_in_assets_and_liabilities_from_operating_activities",
    "단기감융상품의증가": "increase_in_shortterm_financial_instruments",
    "연구자금정산이익": "other_nonoperating_revenues",
    "자기지분상품매입약정": "cash_flows_from_financing_activities",
    "이주비": "other_operating_expenses",
    "운휴중인자산": "property_plant_and_equipment",
    "기타지본항목": "stockholders_equity",
    "공동기업손익": "losses_on_valuation_of_equity_method_securities",
    "체무면제이익": "other_nonoperating_revenues",
    "전속권의증가": "intangible_assets",
    "단기": "shortterm_borrowings",
    "기부금조정": "donations",
    "리스원금반환": "cash_flows_from_financing_activities",
    "미수법인환급액": "prepaid_expenses",
    "자산,부채의증가": "changes_in_assets_and_liabilities_from_operating_activities",
    "영업외이익(손실)": "other_nonoperating_gainslosses",
    "이전대가의감소": "cash_flows_from_investing",
    "다.자산및부채의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "다.영엽활동자산.부채의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "거래일손익조정": "other_nonoperating_gainslosses",
    "리스채권원금의회수": "trade_and_other_current_receivables",
    "인력개발비": "employee_benefits_expense",
    "타계정에서대체액": "changes_in_assets_and_liabilities_from_operating_activities",
    "자기지분매입의무의소멸": "cash_flows_from_financing_activities",
    "자가주식의변동": "treasury_stock",
    "정보사업": "other_nonoperating_revenues",
    "보상금의수령": "other_nonoperating_revenues",
    "납기지연손실": "other_nonoperating_expenses",
    "합계.": "net_profit",
    "급료와임금": "salaries_and_wages",
    "기타포관손익재분류조정": "total_comprehensive_income",
    "자본거래": "cash_flows_from_financing_activities",
    "유동성리스채권의감소": "trade_and_other_current_receivables",
    "나.손익조정": "changes_in_assets_and_liabilities_from_operating_activities",
    "전대리스투자": "cash_flows_from_investing",
    "자본구성요소의증가": "stockholders_equity",
    "유동성리스채권의회수": "trade_and_other_current_receivables",
    "잡이익(보헙금수령)": "other_nonoperating_revenues",
    "자산양수도거래": "cash_flows_from_investing",
    "기타자산의증가（감소）": "changes_in_assets_and_liabilities_from_operating_activities",
    "자산/부채의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "리스채권현금회수액": "trade_and_other_current_receivables",
}

# Validate all snakeIds
invalid = [(k, v) for k, v in directMappings.items() if v not in sl._snakeToKor]
if invalid:
    print(f"Invalid snakeIds ({len(invalid)}):")
    for k, v in invalid:
        print(f"  {k} -> {v}")
else:
    count = sl.learnBatch(directMappings)
    print(f"Learned: {count}")
    print(f"Total synonyms: {sl.synonymCount}")

    fs = sl._getFinanceSearch()
    codes = fs.getCorpList()["stock_code"].drop_nulls().to_list()
    full = 0
    dist = {}
    for code in codes:
        r = sl.analyzeCompany(code)
        if r.matchRate == 100.0:
            full += 1
        else:
            un = len(r.unmatched)
            dist[un] = dist.get(un, 0) + 1
    print(f"\n100% stocks: {full} / {len(codes)} ({full * 100 / len(codes):.1f}%)")
    for k in sorted(dist.keys()):
        if k <= 5:
            print(f"  {k} unmapped: {dist[k]} stocks")
    sixPlus = sum(v for k, v in dist.items() if k >= 6)
    if sixPlus:
        print(f"  6+ unmapped: {sixPlus} stocks")
