import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
from core.dart.searchDart.finance.v7.synonymLearner import SynonymLearner

sl = SynonymLearner()
fs = sl._getFinanceSearch()
corpDf = fs.getCorpList()
codes = corpDf["stock_code"].drop_nulls().to_list()

allUnmatched = set()
for code in codes:
    try:
        r = sl.analyzeCompany(code)
        for acc in r.unmatched:
            allUnmatched.add(acc)
    except:
        pass

alreadyLearned = set(sl._synonyms.keys())
remaining = allUnmatched - alreadyLearned
print(f"Total remaining unique unmapped: {len(remaining)}")

keywordMap = {
    "미착품": "goods_in_transit",
    "재공품": "work_in_process",
    "반제품": "semifinished_goods",
    "원재료": "raw_materials",
    "부재료": "raw_materials",
    "저장품": "supplies",
    "선급금": "advance_payments",
    "선금금": "advance_payments",
    "선급비용": "prepaid_expenses",
    "선납세금": "prepaid_income_tax",
    "선납관세": "other_current_assets",
    "선납부가": "other_current_assets",
    "미수금": "other_receivables",
    "미수수익": "accrued_income",
    "받을어음": "trade_receivables",
    "관세환급": "other_current_assets",
    "가지급금": "other_current_assets",
    "임차보증금": "longterm_guarantee",
    "전세보증금": "longterm_guarantee",
    "임차권리금": "other_noncurrent_assets",
    "회원권": "membership",
    "시설물이용": "membership",
    "전신전화": "membership",
    "공구기구": "tools",
    "공구와기구": "tools",
    "공구과기구": "tools",
    "비품": "furniture_and_fixtures",
    "시설장치": "other_tangible_assets",
    "건설중": "construction_in_progress",
    "미착기계": "goods_in_transit",
    "프로젝트투자": "other_noncurrent_assets",
    "장기투자": "longterm_financial_assets",
    "투자금": "longterm_financial_assets",
    "출자금": "longterm_financial_assets",
    "채굴권": "mining_rights",
    "소프트웨어": "computer_software",
    "전산": "computer_software",
    "디지털자산": "other_intangible_assets",
    "영화투자": "other_noncurrent_assets",
    "미완성드라마": "work_in_process",
    "생물자산": "biological_assets",
    "반환재고": "returnrefund_inventories",
    "반품재고": "returnrefund_inventories",
    "반환자산": "returnrefund_assets",
    "반품자산": "returnrefund_assets",
    "반품충당자산": "returnrefund_assets",
    "반품환불자산": "returnrefund_assets",
    "환불자산": "returnrefund_assets",
    "확정계약자산": "other_current_assets",
    "사외적립": "plan_assets",
    "퇴직연금운용": "plan_assets",
    "퇴직금운용": "plan_assets",
    "사내근로복지": "noncurrent_provisions_for_employee_benefits",
    "리스채권": "finance_lease_receivables",
    "할부채권": "other_receivables",
    "대출채권": "shortterm_loans",
    "미청구채권": "shortterm_gross_amount_due_from_customers_for_contract_work",
    "추가청구공사": "shortterm_gross_amount_due_from_customers_for_contract_work",
    "초과청구공사": "gross_amount_due_to_customers_for_contract_work",
    "미완성주택": "work_in_process",
    "완성주택": "finished_goods",
    "용지": "other_tangible_assets",
    "수입담보금": "other_current_assets",
    "구상채권": "compensation_receivables",
    "특수관계자채권": "trade_receivablesrelated_parties",
    "파생상품자산": "current_derivative_assets",
    "파상상품부채": "derivative_liabilities",
    "파생생품자산": "current_derivative_assets",
    "통화스왑자산": "current_derivative_assets",
    "처분예정자산": "noncurrent_asset_held_for_sale_or_disposal_group",
    "매각예정자산": "noncurrent_asset_held_for_sale_or_disposal_group",
    "공정가치측정자산": "designatedfinancial_assets_at_fv_through_profit",
    "공정가치금융상품": "designatedfinancial_assets_at_fv_through_profit",
    "유동계약자산": "contract_assets",
    "유동계약부채": "contract_liabilities",
    "유동복합금융": "other_current_liabilities",
    "유동회생채권": "other_current_assets",
    "주임종장기채권": "stockholder_executive_employee_longterm_loans",
    "기타당좌자산": "other_current_assets",
    "기타의당좌자산": "other_current_assets",
    "미지급금": "other_payables",
    "미지금금": "other_payables",
    "미지급비용": "accrued_expenses",
    "예수금": "withholdings",
    "예수부가세": "withholdings",
    "선수금": "advance_received",
    "선수수익": "deferred_revenue",
    "가수금": "other_current_liabilities",
    "유동성부채": "current_portion_of_noncurrent_liabilities",
    "외상매입금": "trade_payables",
    "장기미지금금": "other_noncurrent_payables",
    "반품충당부채": "returned_products_provisions",
    "반품추정부채": "returned_products_provisions",
    "비유동성반환부채": "returned_products_provisions",
    "환불부채": "returnrefund_liabilities",
    "금융보증부채": "guarantee_contracts_provisions",
    "연차수당부채": "accrued_expenses",
    "유동장기채무": "current_portion_of_noncurrent_liabilities",
    "처분예정부채": "liabilities_included_in_disposal_groups_classified_as_held_for_sale",
    "특수관계자채무": "trade_payablesrelated_parties",
    "책임이행적립금": "longterm_provisions",
    "수출액": "sales_of_finished_goods",
    "수선유지": "repairs_and_maintenance_expenses",
    "수선비": "repairs_and_maintenance_expenses",
    "여비교통": "traveling_expenses",
    "해외출장": "traveling_expenses",
    "접대비": "entertainment",
    "해외접대": "entertainment",
    "연차수당": "salaries",
    "제수당": "salaries",
    "포상비": "salaries",
    "사원모집비": "salaries",
    "안전관리비": "other_expenses",
    "홍보비": "sales_promotions",
    "외주비": "outsourcing_expenses",
    "도서신문비": "other_expenses",
    "시험비": "research",
    "경상연구비": "usual_development_and_research_expenses",
    "조업도손실": "other_expenses",
    "온실가스배출비": "other_expenses",
    "지체상금": "other_expenses",
    "발행분담금": "other_expenses",
    "전기오류": "gainslosses_on_prior_period_error_corrections",
    "전기손익수정이익": "gains_on_prior_period_error_corrections",
    "전기손익수정손실": "losses_on_prior_period_error_corrections",
    "회계오류수정": "gainslosses_on_prior_period_error_corrections",
    "회계변경": "accumulated_effect_of_accounting_policy_change",
    "중단사업이익": "discontinued_operating_incomeloss",
    "중단사업손실": "discontinued_operating_incomeloss",
    "중단사업순이익": "discontinued_operating_incomeloss",
    "중단사업총포괄": "discontinued_operating_incomeloss",
    "계속사업이익": "profit_from_continuing_operations",
    "계속사업영업": "operating_income",
    "계속사업총포괄": "profit_from_continuing_operations",
    "사업부매각이익": "gains_on_disposition_of_subsidiaries",
    "사업매각이익": "gains_on_disposition_of_subsidiaries",
    "영업양도이익": "gains_on_disposition_of_subsidiaries",
    "투자자산처분": "gains_on_disposal_of_assets",
    "투자자산폐기": "losses_on_disposal_of_assets",
    "비유동자산처분": "gains_on_disposal_of_assets",
    "유평자산폐기": "losses_on_disposal_of_assets",
    "확정계약손실": "onerous_contracts_provisions",
    "손해배상": "other_expenses",
    "배상금의수령": "other_income",
    "이자율스왑": "swaptransaction",
    "통화스왑": "swaptransaction",
    "금융보증손익": "gains_on_valuations_of_derivatives",
    "거래일조정": "other_expenses",
    "반품추정손실": "other_expenses",
    "반품충당손실": "other_expenses",
    "개발비감액손실": "impairment_losses_on_assets",
    "리스변경차손": "other_expenses",
    "리스정산이익": "other_income",
    "외화차익": "gains_on_foreign_currency_transactions",
    "외화화산이익": "gains_on_foreign_currency_transactions",
    "해외사업환산": "gains_on_foreign_currency_translation",
    "해외사업장처분": "gains_on_foreign_currency_translation",
    "해외산업손익": "gains_on_foreign_currency_translation",
    "환율차이": "difference_by_changes_in_foreign_exchange_rates",
    "지분증권평가": "gains_on_valuations_of_derivatives",
    "장기투자금융상품평가이익": "gains_on_valuations_of_derivatives",
    "장기투자금융상품평가손실": "losses_on_valuations_of_derivatives",
    "단기매매증권평가": "gains_on_valuation_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "장기금융평가": "losses_on_valuations_of_derivatives",
    "단기금융상품평가": "gains_on_valuation_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "관계회사투자이익": "gains_on_valuation_of_investments",
    "관계회사전출": "gainslosses_in_subsidiaries",
    "공동지배기업투자이익": "gains_on_valuation_of_investments_in_joint_ventures",
    "공동지배기업투자손실": "losses_on_valuation_of_investments_in_joint_ventures",
    "공동기업투자이익": "gains_on_valuation_of_investments_in_joint_ventures",
    "공동기업투자주식손익": "gains_on_valuation_of_investments_in_joint_ventures",
    "공동지배기업손실": "losses_on_valuation_of_investments_in_joint_ventures",
    "종속회사및관계회사손익": "gainslosses_in_subsidiaries",
    "종속회사투자처분": "gains_on_disposition_of_subsidiaries",
    "자본거래이익": "other_income",
    "제품평가손실환입": "recovery_of_impairment_losseswritedown_on_inventories",
    "재측정이익": "remeasurement_elements_of_defined_benefit_plans",
    "재측정손실": "remeasurement_elements_of_defined_benefit_plans",
    "유효이자율": "interest_income",
    "타계정대체": "other_adjustments",
    "타계정으로대체": "other_adjustments",
    "비지배분": "net_profitnoncontrolling_interests_equity",
    "비지배부분": "net_profitnoncontrolling_interests_equity",
    "비지배주주지분의증감": "increase_in_noncontrolling_interests_equity",
    "비지배투자자부채": "noncontrolling_interests_equity",
    "지배기업의무상감자": "decrease_in_capital_stock",
    "종속회사의무상감자": "decrease_in_capital_stock",
    "보통주무상증자": "increase_in_capital_stock",
    "증자": "increase_in_capital_stock",
    "자본증가": "increase_in_capital_stock",
    "종속회사지분증가": "increase_in_noncontrolling_interests_equity",
    "종속회사지분변동": "gainslosses_in_subsidiaries",
    "종속회사의자본변동": "gainslosses_in_subsidiaries",
    "종속회사신규설립": "acquisition_of_interest_in_subsidiaries",
    "주식분할": "change_in_capital_stock",
    "주식매수권행사": "exercise_of_stock_options",
    "주식매선택권행사": "exercise_of_stock_options",
    "주식매입선택권소멸": "reversal_of_compensation_expenses_associated_with_stock_options",
    "우리사주": "treasury_stock",
    "지분변동차액": "gainslosses_in_subsidiaries",
    "지분변동차이": "gainslosses_in_subsidiaries",
    "감자차익이입": "other_reserves",
    "기타자본거래": "other_reserves",
    "합병": "change_by_merger_and_acquisition",
    "합볍": "change_by_merger_and_acquisition",
    "인적분할": "change_by_merger_and_acquisition",
    "동일지배": "change_by_merger_and_acquisition",
    "영업양수": "change_by_merger_and_acquisition",
    "사업양수": "cash_outflows_from_merger_and_acquisition",
    "교환대가": "other_reserves",
    "교환권조정": "other_reserves",
    "전환가대가": "other_reserves",
    "복합금융상품대체": "other_reserves",
    "지배력의상실": "gainslosses_in_subsidiaries",
    "조건부대가": "other_reserves",
    "풋옵션행사": "other_reserves",
    "옵션의행사": "other_reserves",
    "주식청약증거금": "other_reserves",
    "소유자와의거래": "other_reserves",
    "자본간계정대체": "other_reserves",
    "기초자본": "other_reserves_at_the_beginning_of_year",
    "기타포괄": "accumulated_other_comprehensive_income",
    "총포괄이익": "comprehensive_income",
    "당기순이익(손실)합계": "net_profit",
    "분기총포괄": "comprehensive_income",
    "반기총포괄": "comprehensive_income",
    "지배지분손익": "net_profitowners_of_parent_equity",
    "중단사업주당순이익": "eps",
    "퇴직연금납입": "plan_assets",
    "퇴직연금의가입": "plan_assets",
    "퇴직금전입액": "provision_for_retirement_allowance",
    "장기금융상품의불입": "increase_in_longterm_financial_instruments",
    "장기금융상품의증가": "increase_in_longterm_financial_instruments",
    "(1)장기금융상품의증가": "increase_in_longterm_financial_instruments",
    "9.장기금융상품의증가": "increase_in_longterm_financial_instruments",
    "8.장기금융상품의증가": "increase_in_longterm_financial_instruments",
    "10.장기금융상품의증가": "increase_in_longterm_financial_instruments",
    "3.장기금융상품의감소": "decrease_in_longterm_financial_instruments",
    "1.단기금융상품의처분": "decrease_in_shortterm_financial_instruments",
    "단기기타금융상품의감소": "decrease_in_shortterm_financial_instruments",
    "당기손익인식자산의증가": "increase_in_shortterm_financial_instruments",
    "당기손익인식금융상품의처분": "decrease_in_shortterm_financial_instruments",
    "당기손익인식지정자산의처분": "decrease_in_shortterm_financial_instruments",
    "단기매매증권의순증가": "increase_in_shortterm_financial_instruments",
    "단기매매증권의증감": "increase_in_shortterm_financial_instruments",
    "장기투자증권의감소": "decrease_in_longterm_financial_instruments",
    "매도가증증권": "longterm_availableforsale_financial_assets",
    "투자주식의감소": "disposal_of_investments_in_associates",
    "종속회사주식의증가": "acquisition_of_interest_in_subsidiaries",
    "단기투자자산의회수": "decrease_in_shortterm_financial_instruments",
    "정책의변경": "accumulated_effect_of_accounting_policy_change",
    "기초재무제표수정": "accumulated_effect_of_accounting_policy_change",
    "단기차임금": "shortterm_borrowings",
    "금융업채권": "trade_receivables",
    "기타비유동금융채권": "lt_trade_and_other_receivables",
    "장기기타재권": "lt_trade_and_other_receivables",
    "장기기타부채": "other_noncurrent_liabilities",
    "기타재권의증가": "increase_in_other_receivables",
    "기타의비유동부채의감소": "decrease_in_other_noncurrent_liabilities",
    "기타비유동부채증가": "increase_in_other_noncurrent_liabilities",
    "기타비유동부채의순증가": "increase_in_other_noncurrent_liabilities",
    "주임종단기채권의대여": "increase_in_shortterm_loans",
    "주임종단기채무의감소": "decrease_in_other_payables",
    "환매조건부매도의증감": "bonds_sold_under_repurchase_agreements",
    "당기손익-공정가치지분상품": "designatedfinancial_assets_at_fv_through_profit",
    "당기손익-공정가치채무상품": "designatedfinancial_assets_at_fv_through_profit",
    "당기손익-공정가치측정자산": "designatedfinancial_assets_at_fv_through_profit",
    "당기손익공정가치": "designatedfinancial_assets_at_fv_through_profit",
    "비유동금융리스채권": "finance_lease_receivables",
    "유동성금융리스채권": "finance_lease_receivables",
    "리스채권의원금": "finance_lease_receivables",
    "장기투자자산평가": "gains_on_valuation_of_investments",
    "기타금융손익": "other_income",
    "선급기술도입비": "other_current_assets",
    "전산사용료": "computer_software",
    "건설중인자신": "construction_in_progress",
    "시설물이용권의증가": "increase_in_membership",
    "비품의매각": "disposal_of_tangible_assets",
    "시설장치의감소": "disposal_of_tangible_assets",
    "공구기구의증가": "acquisition_of_tangible_assets",
    "장기미지금금": "other_noncurrent_payables",
    "선금금의감소(증가)": "decrease_in_advance_payments",
    "금융보증부채의상각": "other_expenses",
    "금융보증부채평가이익": "other_income",
    "상품의증가(감소)": "change_in_inventory_of_finished_goods_and_work_in_process",
    "부재료의감소(증가)": "change_in_inventory_of_finished_goods_and_work_in_process",
    "선납세금의증가": "increase_in_other_current_assets",
    "선납세금의감소": "decrease_in_other_current_assets",
    "부가세대금금": "other_current_assets",
    "가수금의증가(감소)": "increase_in_other_current_liabilities",
    "미지금금의증가(감소)": "increase_in_other_payables",
    "상품수출액": "sales_of_merchandise",
    "정보보조금의증가": "government_grants",
    "반품제품회수권의감소": "returnrefund_assets",
    "반품충당자산의감소(증가)": "returnrefund_assets",
    "반환재고회수권의증가(감소)": "returnrefund_inventories",
    "반품추정부채의증가": "returned_products_provisions",
    "환불부채환입": "returnrefund_liabilities",
    "유동성계약부채의증가(감소)": "contract_liabilities",
    "리스채권의증가(감소)": "finance_lease_receivables",
    "확정계약부채의증가(감소)": "other_current_liabilities",
    "금융보증부채의대위변제": "other_expenses",
    "건설중인자산의증감": "construction_in_progress",
    "확정계약자산의감소(증가)": "other_current_assets",
    "소프트웨어의감소": "decrease_in_computer_software",
    "기타의자산의증가": "increase_in_other_current_assets",
    "기타의부채의증가(감소)": "increase_in_other_current_liabilities",
    "가지급금의증가(감소)": "other_current_assets",
    "미상각신계약비": "other_noncurrent_assets",
    "단기선급세금": "prepaid_income_tax",
    "출자금의분배": "decrease_in_longterm_financial_instruments",
    "기타의기타비유동자산": "other_noncurrent_assets",
    "기타비유동자산감소(증가)": "decrease_in_other_noncurrent_assets",
    "재무상태표상현금": "cash_and_cash_equivalents",
    "기타비유동부채.": "other_noncurrent_liabilities",
    "기타유동자산.": "other_current_assets",
    "기타비유동자산.": "other_noncurrent_assets",
    "2.기타채무": "other_payables",
    "2.기타비유동채권": "lt_trade_and_other_receivables",
    "기타보종금의감소": "decrease_in_longterm_guarantee",
    "회원권의매각": "decrease_in_membership",
    "회원권의회수": "decrease_in_membership",
    "당기손익인식부채평가이익": "other_income",
    "기타투자유입": "cash_inflows_from_other_investing_activities",
    "해외사업장처분효과": "difference_by_changes_in_foreign_exchange_rates",
    "2018.01.01(조정금액)": "accumulated_effect_of_accounting_policy_change",
    "당기손익-공정가치측정금융상품평가이익": "gains_on_valuation_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익\uff0d공정가치측정금융상품평가이익": "gains_on_valuation_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "기타포괄공정가치측정지분상품평가손익": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "공급설비": "other_tangible_assets",
    "공급자금융약정": "shortterm_borrowings",
    "종속회사": "gainslosses_in_subsidiaries",
    "관계회사": "gains_on_valuation_of_investments",
    "퇴직연금": "plan_assets",
    "자산및부채": "other_adjustments",
    "자산,부채": "other_adjustments",
    "기타자본의": "other_reserves",
}

autoMappings = {}
for acc in remaining:
    for keyword, snakeId in keywordMap.items():
        if keyword in acc and snakeId in sl._snakeToKor:
            autoMappings[acc] = snakeId
            break

print(f"Auto-mappable: {len(autoMappings)}")

if autoMappings:
    count = sl.learnBatch(autoMappings)
    print(f"Learned: {count}")
    print(f"Total synonyms: {sl.synonymCount}")

# Check new stats
done = 0
dist = {}
for code in codes:
    try:
        r = sl.analyzeCompany(code)
        if r.unmatchedCount == 0:
            done += 1
        else:
            bucket = min(r.unmatchedCount, 11)
            dist[bucket] = dist.get(bucket, 0) + 1
    except:
        pass

print("\n=== Result ===")
print(f"100% stocks: {done} / {len(codes)} ({done / len(codes) * 100:.1f}%)")
for k in sorted(dist.keys()):
    label = f"{k}+" if k == 11 else str(k)
    print(f"  {label} unmapped: {dist[k]} stocks")
