import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
sys.path.insert(0, ".")
from core.dart.searchDart.finance.v7.synonymLearner import SynonymLearner

sl = SynonymLearner()
print(f"학습 전 동의어: {sl.synonymCount}")

mappings = {
    # === 영업에서 창출된 현금 (오타/변형) ===
    "1)영업에서창출된현금흐름": "cash_flows_from_operatings",
    "4.영업에서창출된현금(1+2+3)": "cash_flows_from_operatings",
    "영업에서창출한현금흐름": "cash_flows_from_operatings",
    "영업에서충출된현금흐름": "cash_flows_from_operatings",
    "영업에창출된현금흐름": "cash_flows_from_operatings",
    "영업으로부터창촐된현금흐름": "cash_flows_from_operatings",
    "영업으로부터창출한현금흐름": "cash_flows_from_operatings",
    "영엉활동으로부터창출된현금흐름": "cash_flows_from_operatings",
    "현금흐름에서창출된현금흐름": "cash_flows_from_operatings",
    "사업활동으로인한현금흐름": "cash_flows_from_operatings",
    # === 당기순이익 조정 ===
    "(1)분기순손실": "net_income",
    "(2)수익.비용의조정": "net_income",
    "3.자산및부채의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "3.현금의유입이없는수익등의차감": "net_income",
    "<비현금조정>": "net_income",
    "<운전자본조정>": "changes_in_assets_and_liabilities_from_operating_activities",
    "당기순이익(분기순이익)": "net_income",
    "당기순이익(조정)": "net_income",
    "당기순이익조정을위한가감(비용)": "net_income",
    "당기순익에대한조정": "net_income",
    "딩기순이익에대한조정": "net_income",
    "반기순익에대한조정": "net_income",
    "당/분기순이익": "net_income",
    "당기손손익": "net_income",
    "당기손익-공정가치측정": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "전분기순이익": "net_income",
    "당기총포괄이익:": "other_comprehensive_income",
    "(2)당기순이익(손실)조정을위한가감": "net_income",
    "비현금항목의조정(주26)": "net_income",
    "비현금흐름의조정": "net_income",
    "현금유출입이없는비용등의가산": "addition_of_expenses_of_noncash_transactions",
    "현금유출입이없는수익등의차감": "net_income",
    "현금의유촐이없는비용의가산": "addition_of_expenses_of_noncash_transactions",
    # === 운전자본/자산부채 변동 ===
    "운전자본의순증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "자산.부채증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "자신및부채의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "영엽활동자산부채의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    # === IFRS 관련 ===
    "IFRS15조정": "retained_earnings",
    "K-IFRS1115조정": "retained_earnings",
    "K-IFRS1116조정": "retained_earnings",
    "기업회계기준제1116호최조적용조정": "retained_earnings",
    "회계기준변경에따른효과": "retained_earnings",
    "회계변경으로인한효과": "retained_earnings",
    "회계정책의변경수정후": "retained_earnings",
    "회계정책의변경의누적효과": "retained_earnings",
    # === 기초/기말/수정 ===
    "(기초)재작성금액": "retained_earnings",
    "기초(재작성후금액)": "retained_earnings",
    "2016.09.30(전분기말)": "retained_earnings",
    "2016.1.1(전기초)": "retained_earnings",
    "2016.12.31(전기말)": "retained_earnings",
    "2017.09.30(당분기말)": "retained_earnings",
    "2017.1.1(당기초)": "retained_earnings",
    "2020.01.01(수정후전전기초)": "retained_earnings",
    "수정후기초작액(기준변경)": "retained_earnings",
    "수정후기초잔액(기준변경)": "retained_earnings",
    "재무제표재작성후": "retained_earnings",
    "전기초수정전": "retained_earnings",
    "처리후기초자본": "retained_earnings",
    # === 계약자산/부채 ===
    "계약부자산의감소(증가)": "other_current_assets",
    "계약부채(환불부채)": "other_current_liabilities",
    "계약부채의변동": "other_current_liabilities",
    "계약원가자산의감소(증가)": "other_current_assets",
    "계약원가자산의증가": "other_current_assets",
    "계약자산(환불자산)": "other_current_assets",
    "계약자산의변동": "other_current_assets",
    "반환재고회수권": "other_current_assets",
    "반품제품회권": "other_current_assets",
    "반품회수권": "other_current_assets",
    "환불자산의감소": "other_current_assets",
    # === 지배기업/비지배 귀속 ===
    "반기순손익의귀속": "net_income",
    "반기순이익(손실)의귀속": "net_income",
    "분기순손익의귀속": "net_income",
    "포괄손익의귀속": "other_comprehensive_income",
    "지배기업소유주지분이익(손실)": "net_income",
    "지배기업소유지주지분순이익(손실)": "net_income",
    "지배기업에귀속되는당기순이익(손실)": "net_income",
    "지배기업의소유주에귀속되는당기순이익": "net_income",
    "지배기업의소유주에귀속될반기순이익(손실)": "net_income",
    "지배주주순손실": "net_income",
    "지배주주순이익(손실)": "net_income",
    "지배주주포괄손실": "other_comprehensive_income",
    "지배지분의소유지분": "total_stockholders_equity",
    "지배지분포괄이익(손실)": "other_comprehensive_income",
    "지배회사소유지분": "total_stockholders_equity",
    "지배회사의소유주에귀속될당기순이익": "net_income",
    "비지배기업의소유주에게귀속되는자본": "noncontrolling_interests_equity",
    "비지배주주순이익(손실)": "noncontrolling_interests_equity",
    "비지배부분의처분": "noncontrolling_interests_equity",
    "비재배지분과의거래로인한현금유출": "noncontrolling_interests_equity",
    "비재배지분증가": "noncontrolling_interests_equity",
    "지배분자본변동": "total_stockholders_equity",
    # === 종속/관계기업 ===
    "관계기업투자주식취득변동": "investments_in_associates",
    "관계및공동기업투자이익": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계사수출용설비처분": "gains_on_disposition_of_investments",
    "관계지업투자손익": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "관계회사주식처분": "gains_on_disposition_of_equity_method_securities",
    "공동기업투자지분": "investments_in_joint_ventures",
    "공동약정기업배분차액": "investments_in_joint_ventures",
    "공동투자기업손실": "gainslosses_in_subsidiaries_joint_ventures_associates",
    "종속,관기업처분순현금유입": "gains_on_disposition_of_subsidiaries",
    "종속,관기업투자주식의처분": "gains_on_disposition_of_subsidiaries",
    "종속기업의처분으로인한유입": "gains_on_disposition_of_subsidiaries",
    "종속기업의처분으로인한유출": "investments_in_subsidiaries",
    "종속기업투자주식의출자": "investments_in_subsidiaries",
    "종속회사투자차액": "investments_in_subsidiaries",
    "조인트벤처자본변동": "investments_in_joint_ventures",
    "지분빕이익": "gains_on_valuation_of_equity_method_securitiesequity_method_note",
    # === 유동화/장기부채 ===
    "유동화부채의발행": "longterm_borrowings",
    "유동화채무의발행": "longterm_borrowings",
    "장기유동화부채의발행": "longterm_borrowings",
    "장기유동화채무발행": "longterm_borrowings",
    "장기유동화채무의발행": "longterm_borrowings",
    "장기유동채무": "longterm_borrowings",
    "유동성회생담보채무의상환": "current_portion_of_longterm_debt",
    "유동성장기차입금순증감": "current_portion_of_longterm_borrowings",
    # === 리스 관련 ===
    "리스개설원가의지급": "lease_obligations",
    "리스개설직접원가지급": "lease_obligations",
    "리스상환손실": "decrease_in_lease_obligations",
    "리스회수손실": "decrease_in_lease_obligations",
    "리스회수이익": "decrease_in_lease_obligations",
    "유동성리스부채": "lease_obligations",
    # === 주식/자본 관련 ===
    "감자및증자비용": "capital_increase_decrease_without_consideration",
    "납입자본의증가": "paid_in_capital_increase",
    "우리사주조합에대한신주발행": "paid_in_capital_increase",
    "주식발행비의지출": "paid_in_capital_increase",
    "주식발행비의환급": "paid_in_capital_increase",
    "주식발행초과금의이익잉역금전입": "paidin_capital_in_excess_of_par_value",
    "주식발행초과금의증가": "paidin_capital_in_excess_of_par_value",
    "주식발행초과금전입": "paidin_capital_in_excess_of_par_value",
    "주식병합단주처리": "capital_stock",
    "액면병합으로인한자본변동": "capital_stock",
    "신주청약준비금": "capital_stock",
    "신주인수권행사로자본금증가": "paid_in_capital_increase",
    "신주인수권행사로주식발행초과금증가": "paidin_capital_in_excess_of_par_value",
    "증자관련제비용": "paid_in_capital_increase",
    "증자비용의지급": "paid_in_capital_increase",
    "소유자에의한출자": "paid_in_capital_increase",
    "소유주에의한기타출자에따른증감": "paid_in_capital_increase",
    "자본거래등직접원가": "paid_in_capital_increase",
    "자본내대체": "total_stockholders_equity",
    "자본변동차액": "total_stockholders_equity",
    "소유주와의거래(결손금보전)": "retained_earnings",
    "소유주와의거래(신주발행)": "paid_in_capital_increase",
    "소유주와의거래등총액": "total_stockholders_equity",
    "자본에반영된소유주와이거래등": "total_stockholders_equity",
    "자본에직접반영된주주와의거래총액": "total_stockholders_equity",
    "주주로부터의수증": "other_capital_surplus",
    "기타자본(신주인수대가)": "stock_warrants_conversion_rights",
    "기타자본거래로인한현금유출액": "total_stockholders_equity",
    "기타자본항목": "other_reserves",
    "기타의자본구성요소": "other_reserves",
    "기타의자본조정-": "other_reserves",
    "기타의자본조정유출": "other_reserves",
    "보통주전환계정재분류": "capital_stock",
    "조정후기본자본": "capital_stock",
    # === 주식매수선택권 관련 ===
    "주식기준보상의대체": "stock_options",
    "주식기준보상의지급": "stock_options",
    "주식매수선택": "stock_options",
    "주식매입권적립금[구성요소]": "stock_options",
    "주식매입권행사로인한증가": "exercise_of_stock_options",
    "주식매입선택권대체(행사기간만료)": "stock_options",
    "주식매입선택권의대체": "stock_options",
    # === 신종자본증권 ===
    "신종발행증권발행": "paid_in_capital_increase",
    "신종자본증권교환권행사": "paid_in_capital_increase",
    "신종자본증권발행비": "paid_in_capital_increase",
    "신종자본증권발행비지급": "paid_in_capital_increase",
    "신종자본증권의매수청구권": "paid_in_capital_increase",
    # === 퇴직급여/종업원 ===
    "사외적립자산의불입액": "defined_benefit_assets",
    "사외적립자산의순감소": "defined_benefit_assets",
    "순확정급부채": "defined_benefit_liabilities",
    "장기종업원급여재측정요소": "remeasurement_elements_of_defined_benefit_plans",
    "퇴직연금": "defined_benefit_assets",
    "퇴직연금부담금의변동": "defined_benefit_assets",
    "퇴직연금운용수익": "defined_benefit_assets",
    "퇴직연금운용자산의증": "defined_benefit_assets",
    "퇴직연금운용자산의처분": "defined_benefit_assets",
    "종업원단기채권": "other_current_assets",
    "주임종단기채권": "other_current_assets",
    "주임종단기채권증가": "other_current_assets",
    "상여금": "sga",
    "연차수당지급": "sga",
    "연차수당충당급전입액": "longterm_provisions",
    # === 적립금/준비금 ===
    "이익준비금적립": "retained_earnings",
    "이익준비금적립액": "retained_earnings",
    "법정적립금의처분액": "retained_earnings",
    "법정적립금처분액": "retained_earnings",
    "기업합리화적립": "retained_earnings",
    "적립급의적립": "retained_earnings",
    "준비금의이입": "retained_earnings",
    "이월결손금처리등": "retained_earnings",
    # === 전환사채/사채 ===
    "무보증회사채": "bonds",
    "전환사채상각": "longterm_borrowings",
    "전환사체의발행": "longterm_borrowings",
    "전환상환주보통주전환": "increase_in_preferred_stock_of_redemption",
    "전환우전주증가": "increase_in_preferred_stock_of_redemption",
    "전환증권의주식전환": "paid_in_capital_increase",
    # === 분할/합병 ===
    "분할로인한자본증감": "change_by_merger_and_acquisition",
    "분할로인할자본증감": "change_by_merger_and_acquisition",
    "인적분할로인한증감": "change_by_merger_and_acquisition",
    "합볍으로인한변동": "change_by_merger_and_acquisition",
    # === 장기 채권/금융상품 (오타) ===
    "장기금융상픔의증가": "longterm_financial_instruments",
    "장기금응상품의증가": "longterm_financial_instruments",
    "장기기타비유동채권의감소": "lt_trade_and_other_receivables",
    "장기기타수취채권이감소": "lt_trade_and_other_receivables",
    "장기리스채권의처분": "leasedrightofuse_assets",
    "장기미지금금": "longterm_other_payables",
    "장기미지급증가": "longterm_other_payables",
    "장기선급비용의지급": "advance_payments",
    "장기연구과제보조금의감소": "government_grants_deferred_income",
    "장기연구과제보조금의증가": "government_grants_deferred_income",
    "장기채권및기타채권": "lt_trade_and_other_receivables",
    "장기채권및기타채권의감소(증가)": "lt_trade_and_other_receivables",
    # === 기타 비유동 (오타) ===
    "기타비유동금웅부채": "other_longterm_financial_liabilities",
    "기타비유동금융부채의처분": "other_longterm_financial_liabilities",
    "기타비유동금융산": "other_longterm_financial_assets",
    "기타비유동지급채무의증감": "other_noncurrent_liabilities",
    "기타비유동채권및기타채권": "other_noncurrent_assets",
    "기타비유동채권의증가(감소)": "other_noncurrent_assets",
    "기타비유통부채": "other_noncurrent_liabilities",
    # === 기타 유동 ===
    "단기기타채권(주3,5,29)": "other_current_assets",
    "단기매매금융자의감소(증가)": "financial_assets_at_fv_through_profit",
    "단기매매금융지산": "financial_assets_at_fv_through_profit",
    "단기매매증권의감소(증가)": "financial_assets_at_fv_through_profit",
    "단기매매증원의처분": "financial_assets_at_fv_through_profit",
    "단기차임금의상환": "shortterm_borrowings",
    "단기투자산의증가": "shortterm_financial_instruments",
    "단기투자자산의증가": "shortterm_financial_instruments",
    "기타단기미지급비용": "other_payables",
    # === 기타 ===
    "1.당좌자산": "current_assets",
    "공해방지비": "sga",
    "관세미수금의감소(증가)": "other_receivables",
    "교환권대가의증가": "consideration_for_conversion_rights",
    "국고보고금의증가": "government_grants_deferred_income",
    "국민연금전환금의순감소": "defined_benefit_assets",
    "금융리스비품": "leased_assets",
    "금융보증채무손실(환입)": "increasedecrease_in_financial_guarantee_provisions",
    "금융수익에대한조정(원가)": "interest_income",
    "금융수익의조정": "interest_income",
    "금융업자산의감소": "other_current_assets",
    "금융업자산의증가": "other_current_assets",
    "기타금유부채의차입": "other_current_financial_liabilities",
    "기타비금융상품감소(증가)": "other_current_assets",
    "기타비용지급": "sga",
    "기타소유자와의거래": "total_stockholders_equity",
    "기타손익(손실)": "other_nonoperating_income",
    "기타수쉬채권의감소(증가)": "other_receivables",
    "기타수채채권의감소": "other_receivables",
    "기타순익": "other_nonoperating_income",
    "기타요구불예금": "cash_and_cash_equivalents",
    "기타유동자산손상차손조정": "other_current_assets",
    "기타차이": "net_income",
    "기타충동부채": "other_current_liabilities",
    "기타포괄손액누계액": "accumulated_other_comprehensive_income",
    "당기손익공정가치측정금융상품의감소(증가)": "financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기손익으로재분류되는항목:": "other_comprehensive_income",
    "당기손익인식자산의순증감": "financial_assets_at_fv_through_profit",
    "당기손익인신금융자산처분이익조정": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_profit_or_loss",
    "당기제품제조원가": "cost_of_sales",
    "당기투자자산": "investment_assets",
    "데이터구매비": "sga",
    "매도청구권": "shortterm_derivative_assets",
    "매도청구권처분": "shortterm_derivative_assets",
    "무상증자비용": "capital_increase_decrease_without_consideration",
    "미수부가세의감소": "other_current_assets",
    "미수부가세의감소(증가)": "other_current_assets",
    "미수부가세의증가": "other_current_assets",
    "미완성공사(분양)": "tangible_assets",
    "미지급의지급": "other_payables",
    "배상금의수취": "other_nonoperating_income",
    "보증채무대위변제": "longterm_provisions",
    "복구의무이행": "provisions_for_restoration_costs",
    "부가가치세자산": "other_current_assets",
    "분배금의수취": "dividends",
    "비용과상계되는국고보조금": "government_grants_deferred_income",
    "비용과상계되는정부보조금": "government_grants_deferred_income",
    "비유동금융상품의감소": "longterm_financial_instruments",
    "비유동자산(금융업)": "noncurrent_assets",
    "사모투자자산": "investment_assets",
    "사업양도로인한자산ㆍ부채의변동": "cash_outflows_by_merger_and_acquisition",
    "상장비용": "sga",
    "상품권의감소(증가)": "other_current_liabilities",
    "상환기술료관련보조금수령액": "government_grants_deferred_income",
    "새계정과목(2)": "other_current_assets",
    "서비스수입": "service_revenue",
    "선급공사원가감소(증가)": "advance_paymentsconstruction_outside_processing_expenses",
    "선급공사원가의증가": "advance_paymentsconstruction_outside_processing_expenses",
    "선급공시원가": "advance_paymentsconstruction_outside_processing_expenses",
    "선수수익증가": "government_grants_deferred_income",
    "소송비용의지급": "longterm_provisions",
    "손실충당비용": "longterm_provisions",
    "수정소급효과(개발비오류등)": "retained_earnings",
    "수정소급효과(수익인식오류등)": "retained_earnings",
    "시설이용권의증가": "intangible_assets",
    "신수인수권대가": "stock_warrants_conversion_rights",
    "업무추진비,판관비": "sga",
    "원재료의감소(증가)": "inventories",
    "위험회피": "shortterm_derivative_assets",
    "유동자산(금융업)": "current_assets",
    "유동파생품자산": "shortterm_derivative_assets",
    "유동확정계약부채의증가(감소)": "other_current_liabilities",
    "유동확정계약부채의？증가(감소)": "other_current_liabilities",
    "이자율스왑": "shortterm_derivative_assets",
    "자기수직거래에따른증가(감소)": "treasury_stock",
    "재고자산평가방법금액효과반영": "inventories",
    "재고자산평가방법금액효과방법": "inventories",
    "저장품의감소(증가)": "inventories",
    "전기금융채권오류": "retained_earnings",
    "전대리스채권(비유동)": "leasedrightofuse_assets",
    "전대리스채권회수": "leasedrightofuse_assets",
    "전산유지비": "sga",
    "정보보조금의상환": "government_grants_deferred_income",
    "제3자지정콜옵션회계처리": "shortterm_derivative_assets",
    "지급보증부채의지급": "increasedecrease_in_financial_guarantee_provisions",
    "지배력의상실로인한현금유입액": "gains_on_disposition_of_subsidiaries",
    "지분상품": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "지원금이익": "other_nonoperating_income",
    "집기비품감소": "tangible_assets",
    "차감매출(유상사급)": "sales",
    "차랑운반구의처분": "disposal_of_tangible_assets",
    "차량매매원가": "cost_of_sales",
    "채무상품": "financial_assets_at_amortised_cost",
    "청약증거금의증가": "other_current_liabilities",
    "초과청구공사증가": "other_current_liabilities",
    "총당부채": "longterm_provisions",
    "통화스왑평가손익": "future_transaction",
    "투자비의회수": "investment_assets",
    "투자유치비용의증가": "sga",
    "특정금융신탁의증가": "longterm_financial_instruments",
    "특허권의지급": "intangible_assets",
    "파생생품의처분": "shortterm_derivative_assets",
    "판권의감소(증가)": "intangible_assets",
    "판권의증가": "intangible_assets",
    "판매촉진비,판관비": "sga",
    "포괄손익-공정가치측청금융자산의증가": "financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "프로젝트투자금의감소": "project_investment",
    "프로젝트투자금의증가": "project_investment",
    "해외사업장외한차이": "reserve_of_exchange_differences_on_translation",
    "해외사업환신이익": "reserve_of_exchange_differences_on_translation",
    "현금및현금등가물": "cash_and_cash_equivalents",
    "회생채권의감소": "other_receivables",
    "후속적으로당기손익으로재분류할수있는항목": "other_comprehensive_income",
    "공정가치근융자평가손익": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "공정가치평가_지분증권_처분손익": "gains_on_disposal_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "공정가치평가손익": "gainslosses_on_valuation_of_financial_assets_measured_at_fair_value_through_other_comprehensive_income",
    "공급자금융약정으로감소": "other_current_liabilities",
    "계열사전출입으로인한증가(감소)": "gainslosses_in_subsidiaries",
    "경상개발연구비": "usual_development_and_research_expenses",
    "단주매각대금": "other_nonoperating_income",
    "사업결합효과": "change_by_merger_and_acquisition",
    "출자전환채무의증가": "longterm_borrowings",
    "소요주와의거래총액": "total_stockholders_equity",
    "중단사업으로인한효과": "discontinued_operating_incomeloss",
}

# snakeId 유효성 검증
validMappings = {k: v for k, v in mappings.items() if v in sl._snakeToKor}
invalidMappings = {k: v for k, v in mappings.items() if v not in sl._snakeToKor}

print(f"유효: {len(validMappings)}개, 무효: {len(invalidMappings)}개")
if invalidMappings:
    for k, v in list(invalidMappings.items())[:10]:
        print(f"  {k} -> {v}")

count = sl.learnBatch(validMappings)
print(f"\n학습: {count}개")
print(f"동의어: {sl.synonymCount}")
