import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
sys.path.insert(0, ".")
from core.dart.searchDart.finance.v7.synonymLearner import SynonymLearner

sl = SynonymLearner()

directMappings = {
    "유동화회사자본병동": "stockholders_equity",
    "유동화회사자본변동": "stockholders_equity",
    "교환권파생부채": "shortterm_derivative_liabilities",
    "유동화부채의상환": "cash_flows_from_financing_activities",
    "유동화부채의차입": "cash_flows_from_financing_activities",
    "조합분담금평가이익": "other_nonoperating_revenues",
    "품질보증비환입": "other_nonoperating_revenues",
    "채무보증환입": "other_nonoperating_revenues",
    "기타장기부채의증가": "other_noncurrent_liabilities",
    "기타단기자산의감소(증가)": "changes_in_assets_and_liabilities_from_operating_activities",
    "옵션거래손실": "other_nonoperating_expenses",
    "매도주가지수옵션": "shortterm_derivative_assets",
    "매수주가지수옵션의증가": "cash_flows_from_investing",
    "이자율스평가이익": "other_nonoperating_revenues",
    "매수주가지수옵션의처분": "cash_flows_from_investing",
    "선박장비품": "property_plant_and_equipment",
    "매도주가지수옵션의처분": "cash_flows_from_investing",
    "기타투자손실": "other_nonoperating_expenses",
    "파생부채의결제": "cash_flows_from_investing",
    "투자손실(주29)": "other_nonoperating_expenses",
    "기타비유동성채권의감소": "cash_flows_from_investing",
    "기타비유동성채무의증가": "cash_flows_from_financing_activities",
    "기타비유동성채권의회수": "cash_flows_from_investing",
    "기타비유동성채권의증가": "cash_flows_from_investing",
    "기타비유동성채무의감소": "cash_flows_from_financing_activities",
    "민원대행": "other_nonoperating_revenues",
    "채권추심": "other_nonoperating_revenues",
    "신용조사": "other_nonoperating_revenues",
    "성과급": "salaries_and_wages",
    "다.순운전자본의변동(주석26)": "changes_in_assets_and_liabilities_from_operating_activities",
    "다.순운전자본의변동(주석27)": "changes_in_assets_and_liabilities_from_operating_activities",
    "3.순운전자본의변동(주석26)": "changes_in_assets_and_liabilities_from_operating_activities",
    "다.장기금융상품의처분": "cash_flows_from_investing",
    "잔여자산의배분": "cash_flows_from_financing_activities",
    "잔여재산배분": "cash_flows_from_financing_activities",
    "잡이익(변제)": "other_nonoperating_revenues",
    "누적유급휴가": "other_current_liabilities",
    "누적유급휴가비": "other_current_liabilities",
    "누적유급휴가의증가": "changes_in_assets_and_liabilities_from_operating_activities",
    "누적유급휴가의증가(감소)": "changes_in_assets_and_liabilities_from_operating_activities",
    "자산양도에따른현금흐름": "cash_flows_from_investing",
    "자산양도로인한현금흐름": "cash_flows_from_investing",
    "유동성기타자산": "other_current_assets",
    "기타유동금융상품의증가": "cash_flows_from_investing",
    "파생생품평가손실": "losses_on_valuations_of_derivatives",
    "기타재무의증가(감소)": "cash_flows_from_financing_activities",
    "파생생품거래이익": "gains_on_valuations_of_derivatives",
    "기타재무의증가": "cash_flows_from_financing_activities",
    "기타의유동채무의증가": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타의비유동채무의증가": "other_noncurrent_liabilities",
    "기타의비유동채무의감소": "other_noncurrent_liabilities",
    "방송프로그램수입": "sales",
    "출연료수입": "sales",
    "제작지원수입": "sales",
    "판권매출": "sales",
    "리스변경이익에대한조정": "changes_in_assets_and_liabilities_from_operating_activities",
    "피트니스수입조정": "changes_in_assets_and_liabilities_from_operating_activities",
    "피트니스수입": "sales",
    "신용평가수입": "sales",
    "채권추심료수입": "sales",
    "신용조회수입": "sales",
    "신용조사수입": "sales",
    "유효세율의변동효과": "taxes_expenses",
    "유효세율의변동": "taxes_expenses",
    "유효세율의변동효과계": "taxes_expenses",
    "IV.기타손익": "other_nonoperating_gainslosses",
    "기타조정(전기수정)": "changes_in_assets_and_liabilities_from_operating_activities",
    "V.금융손익": "net_interest_expenses",
    "전환청구권의보통주전환": "paid_in_capital_increase",
    "기타의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "관리보수": "salaries_and_wages",
    "성과보수": "salaries_and_wages",
    "정부정산손실": "other_nonoperating_expenses",
    "정부정산이익": "other_nonoperating_revenues",
    "유급연차휴가부채의감소": "changes_in_assets_and_liabilities_from_operating_activities",
    "유급휴가부채의감소": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타불입자본)": "capital_surplus",
    "유급연차휴가부채의증가(감소)": "changes_in_assets_and_liabilities_from_operating_activities",
    "유급연차휴가부채의증가": "changes_in_assets_and_liabilities_from_operating_activities",
    "유통보통주식": "net_profit",
    "유통보통주식수": "net_profit",
    "유보통주식수": "net_profit",
    "통하선도거래손실": "other_nonoperating_expenses",
    "기타비유동투자자산의처분": "cash_flows_from_investing",
    "퇴직의이관액": "severance_and_retirement_benefits",
    "기타유동투자자산의처분": "cash_flows_from_investing",
    "납입자본의증감": "paid_in_capital_increase",
    "순운전자금의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "통신장비": "property_plant_and_equipment",
    "단금융상품의감소": "decrease_in_shortterm_financial_instruments",
    "기타비유동부태의증가(감소)": "other_noncurrent_liabilities",
    "유동성자기부채": "current_portion_of_longterm_debt",
    "임차시설의처분": "cash_flows_from_investing",
    "내재파생자산의처분": "cash_flows_from_investing",
    "임차시설물의폐기": "losses_on_disposal_of_assets",
    "위험회피활동으로인한현금순유입(유출)": "other_cash_flows_from_operating_investing_financing_activities",
    "위험회피활동으로인한현금순유입": "other_cash_flows_from_operating_investing_financing_activities",
    "위험회피활동으로인한현금순증감": "other_cash_flows_from_operating_investing_financing_activities",
    "기타금융(비유동)부채의증가": "other_noncurrent_liabilities",
    "기타금융(유동)부채의증가": "other_current_liabilities",
    "기타금융(유동)부채의증가(감소)": "other_current_liabilities",
    "기타부채(유동)의감소": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타특수관계자전출": "cash_flows_from_financing_activities",
    "기타특수관계자전출입": "cash_flows_from_financing_activities",
    "자사주펀드처분": "sale_of_treasury_stock",
    "자사주펀드평가이익": "other_nonoperating_revenues",
    "수입보증": "other_nonoperating_revenues",
    "(3)자산·부채증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "리스거래해지이익": "other_nonoperating_revenues",
    "금융상품거래손실": "other_nonoperating_expenses",
    "금융상품거래이익": "other_nonoperating_revenues",
    "기타비유동채권의증감": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타영업자산부채의증가": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타영업자산부채의감소": "changes_in_assets_and_liabilities_from_operating_activities",
    "유형자폐기손실": "losses_on_disposal_of_assets",
    "기타투자자산의감소(증가)": "cash_flows_from_investing",
    "단기금웅자산의감소": "decrease_in_shortterm_financial_instruments",
    "순운전자번의변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "기터비유동자산": "other_noncurrent_financial_assets",
    "기타변동효과": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타투자자산등의감소": "cash_flows_from_investing",
    "리스변경효과": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타투자자산등의증가": "cash_flows_from_investing",
    "기타유동(채권)의감소(증가)": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타(유동)채권의감소": "changes_in_assets_and_liabilities_from_operating_activities",
    "영업자산부채변동": "changes_in_assets_and_liabilities_from_operating_activities",
    "의장권": "intangible_assets",
    "기타유동성부채의변동": "current_portion_of_longterm_debt",
    "시절장치": "property_plant_and_equipment",
    "기타주자자산의감소": "cash_flows_from_investing",
    "기타투자잔산의증가": "cash_flows_from_investing",
    "기타불입항목": "capital_surplus",
    "리스계약손익": "other_nonoperating_gainslosses",
    "리스계약이익": "other_nonoperating_revenues",
    "자본거래로인한현금유입": "cash_flows_from_financing_activities",
    "기타투자자자산의감소": "cash_flows_from_investing",
    "기타투자자산의순증가": "cash_flows_from_investing",
    "기타투자자산의순변동": "cash_flows_from_investing",
    "기타투자자산의순감소": "cash_flows_from_investing",
    "기타유동성금융채무의증감": "cash_flows_from_financing_activities",
    "리스변경손익": "other_nonoperating_gainslosses",
    "자산·부채의증감:": "changes_in_assets_and_liabilities_from_operating_activities",
    "유동성파생부채의정산": "cash_flows_from_investing",
    "유동성파생부채계약만기": "cash_flows_from_investing",
    "기타(신종교환증권손익)": "other_nonoperating_gainslosses",
    "유동성파생자산계약만기": "cash_flows_from_investing",
    "유동성파생자산의정산": "cash_flows_from_investing",
    "유동성파생자산의계약만기": "cash_flows_from_investing",
    "유동성파생부채의계약만기": "cash_flows_from_investing",
    "유동금융상품의증가": "cash_flows_from_investing",
    "유동채권의증가": "changes_in_assets_and_liabilities_from_operating_activities",
    "기타재권": "other_current_assets",
    "개설집기비품": "tools_and_office_equipment",
    "음식원재료": "raw_materialssubmaterials",
    "음식매출": "sales",
    "방송장비": "property_plant_and_equipment",
    "유동성입회금": "other_current_assets",
    "입회금의상환": "cash_flows_from_investing",
    "입회금": "other_noncurrent_financial_assets",
    "입회금증가": "cash_flows_from_investing",
    "입회금의반환": "cash_flows_from_investing",
    "2.리스채권의회수": "trade_and_other_current_receivables",
    "3.리스채권의회수": "trade_and_other_current_receivables",
    "4.리스채권의회수": "trade_and_other_current_receivables",
}

# Validate all snakeIds
invalid = [(k, v) for k, v in directMappings.items() if v not in sl._snakeToKor]
if invalid:
    print(f"Invalid snakeIds ({len(invalid)}):")
    for k, v in invalid:
        print(f"  {k} -> {v}")
else:
    count = sl.learnBatch(directMappings)
    print(f"Learned: {count}")
    print(f"Total synonyms: {sl.synonymCount}")

    fs = sl._getFinanceSearch()
    codes = fs.getCorpList()["stock_code"].drop_nulls().to_list()
    full = 0
    dist = {}
    for code in codes:
        r = sl.analyzeCompany(code)
        if r.matchRate == 100.0:
            full += 1
        else:
            un = len(r.unmatched)
            dist[un] = dist.get(un, 0) + 1
    print(f"\n100% stocks: {full} / {len(codes)} ({full * 100 / len(codes):.1f}%)")
    if dist:
        for k in sorted(dist.keys()):
            print(f"  {k} unmapped: {dist[k]} stocks")
